"""Gate: `auths/__init__.pyi` must re-export exactly the runtime surface.

`auths` is a `py.typed` package with a lazy `__getattr__`, so a type checker
reads only the stub. Every name missing from the stub is invisible to mypy and
pyright even though it imports at runtime -- which is how the entire production
client became untypeable while `api/public-api.txt` reported it as public.

The stub is generated from `auths.__init__._OWNERS`, the same table the lazy
import uses, so the two cannot disagree.
"""

from __future__ import annotations

import argparse
import importlib
from pathlib import Path

_HEADER = (
    "# Generated by tools/check_type_stub.py from auths.__init__._OWNERS.\n"
    "# Run `python tools/check_type_stub.py --update` after changing the\n"
    "# public root. Never hand-edit: a name only a human remembered to add\n"
    "# here would not exist at runtime.\n"
)


def projection() -> str:
    root = importlib.import_module("auths")
    owners: dict[str, str] = getattr(root, "_OWNERS")
    exported: list[str] = list(getattr(root, "__all__"))
    if sorted(owners) != sorted(exported):
        raise SystemExit(
            "auths.__all__ and auths._OWNERS disagree: "
            f"{sorted(set(owners) ^ set(exported))}"
        )
    lines = [_HEADER]
    for name in sorted(owners):
        lines.append(f"from {owners[name]} import {name} as {name}\n")
    lines.append("\n__all__: list[str]\n")
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update", action="store_true")
    arguments = parser.parse_args()
    stub = Path(__file__).parents[1] / "python" / "auths" / "__init__.pyi"
    actual = projection()
    if arguments.update:
        stub.write_text(actual)
        return
    committed = stub.read_text()
    if committed != actual:
        raise SystemExit(
            "auths/__init__.pyi does not match the runtime public root; "
            "run `python tools/check_type_stub.py --update`"
        )
    symbols = sum(1 for line in actual.splitlines() if line.startswith("from "))
    print(f"Python type stub matches the runtime root ({symbols} symbols)")


if __name__ == "__main__":
    main()
