"""Gate: `auths/__init__.pyi` must re-export exactly the runtime surface."""

from __future__ import annotations

import argparse
import importlib
from pathlib import Path

_HEADER = (
    "# Generated by tools/check_type_stub.py from auths.__init__._OWNERS.\n"
    "# Run `python tools/check_type_stub.py --update` after changing the\n"
    "# public root. Never hand-edit: a name only a human remembered to add\n"
    "# here would not exist at runtime.\n"
)


def projection() -> str:
    root = importlib.import_module("auths")
    exported: list[str] = list(getattr(root, "__all__"))
    owners = {}
    for name in exported:
        owner = getattr(getattr(root, name), "__module__", "auths._public")
        # Dynamically generated enums deliberately advertise the public root
        # for repr/pickle stability, while their import owner remains _public.
        owners[name] = "auths._public" if owner == root.__name__ else owner
        # Runtime type aliases report their implementation owner as `typing`,
        # which is not where the public name can be imported from.
        if name == "OperationState":
            owners[name] = "auths._session"
    lines = [_HEADER.replace("auths.__init__._OWNERS", "auths.__all__")]
    for name in sorted(owners):
        lines.append(f"from {owners[name]} import {name} as {name}\n")
    lines.append("\n__all__: list[str]\n")
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update", action="store_true")
    arguments = parser.parse_args()
    stub = Path(__file__).parents[1] / "python" / "auths" / "__init__.pyi"
    actual = projection()
    if arguments.update:
        stub.write_text(actual)
        return
    committed = stub.read_text()
    if committed != actual:
        raise SystemExit(
            "auths/__init__.pyi does not match the runtime public root; "
            "run `python tools/check_type_stub.py --update`"
        )
    symbols = sum(1 for line in actual.splitlines() if line.startswith("from "))
    print(f"Python type stub matches the runtime root ({symbols} symbols)")


if __name__ == "__main__":
    main()
