//! Product-waist security and parity contract.

use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;

/// Versioned inventory consumed by product SDK conformance runners.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProductWaistManifest {
    /// Schema identifier.
    pub schema: String,
    /// Component that owns the semantic oracles.
    pub semantic_owner: String,
    /// Rust generator for the shared cross-language fixture projection.
    pub fixture_generator: String,
    /// Generated projection containing canonical bytes and stable outcomes.
    pub fixture_projection: String,
    /// Required projection fields generated by Rust.
    pub fixture_fields: Vec<String>,
    /// Ordered invariant cases.
    pub cases: Vec<ProductWaistCase>,
}

/// One security invariant and its cross-language evidence.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProductWaistCase {
    /// Stable case identity.
    pub id: String,
    /// Boundary at which the case must fail or transition.
    pub boundary: String,
    /// Stable expected semantic identity.
    pub expected: String,
    /// Existing tests that execute this invariant.
    pub evidence: ProductWaistEvidence,
}

/// Rust and SDK evidence for one invariant.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProductWaistEvidence {
    /// Rust-owned semantic or lifecycle evidence.
    pub rust: String,
    /// TypeScript SDK evidence.
    pub typescript: String,
    /// Python SDK evidence.
    pub python: String,
}

impl ProductWaistManifest {
    /// Validates the schema, stable identifiers, coverage, and fixture fields.
    ///
    /// # Errors
    ///
    /// Returns a bounded description of the first invalid contract item.
    pub fn validate(&self) -> Result<(), String> {
        if self.schema != "auths.simplified-product-waist-conformance/1"
            || self.semantic_owner != "Rust"
        {
            return Err("unsupported simplified product-waist manifest".to_owned());
        }
        let required_fields = [
            "verdict",
            "stage",
            "code",
            "commitments.action",
            "command",
            "receipts.decision.canonical",
            "receipts.decision.signingPreimage",
            "receipts.execution.canonical",
            "receipts.execution.signingPreimage",
        ];
        for field in required_fields {
            if !self
                .fixture_fields
                .iter()
                .any(|candidate| candidate == field)
            {
                return Err(format!("missing shared fixture field {field}"));
            }
        }
        let mut ids = BTreeSet::new();
        let mut families = BTreeSet::new();
        for case in &self.cases {
            if !valid_id(&case.id) || !ids.insert(case.id.as_str()) {
                return Err(format!(
                    "invalid or duplicate product-waist case {}",
                    case.id
                ));
            }
            let family = case.id.split('/').next().unwrap_or_default();
            families.insert(family);
            if case.boundary.is_empty()
                || case.expected.is_empty()
                || case.evidence.rust.is_empty()
                || case.evidence.typescript.is_empty()
                || case.evidence.python.is_empty()
            {
                return Err(format!("product-waist case {} is incomplete", case.id));
            }
        }
        for family in [
            "command",
            "substitution",
            "delegation",
            "state",
            "provider",
            "cancellation",
            "outcome",
            "transport",
            "receipt",
            "parity",
            "configuration",
        ] {
            if !families.contains(family) {
                return Err(format!("missing product-waist case family {family}"));
            }
        }
        Ok(())
    }
}

/// Returns the Rust-owned simplified product-waist manifest.
#[must_use]
pub fn simplified_product_waist_manifest() -> ProductWaistManifest {
    ProductWaistManifest {
        schema: "auths.simplified-product-waist-conformance/1".to_owned(),
        semantic_owner: "Rust".to_owned(),
        fixture_generator: "bindings/wasm/auths-proof-wasm/examples/generate-node-vectors.rs"
            .to_owned(),
        fixture_projection: "target/binding-vectors/workflow.projection.json".to_owned(),
        fixture_fields: [
            "verdict",
            "stage",
            "code",
            "commitments.action",
            "commitments.result",
            "commitments.plan",
            "command",
            "authorityDiff",
            "receipts.decision.id",
            "receipts.decision.canonical",
            "receipts.decision.signingPreimage",
            "receipts.execution.id",
            "receipts.execution.canonical",
            "receipts.execution.signingPreimage",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect(),
        cases: product_waist_cases(),
    }
}

#[allow(clippy::too_many_lines)]
fn product_waist_cases() -> Vec<ProductWaistCase> {
    let command_rust = "bindings/python/src/mcp.rs";
    let command_typescript = "bindings/typescript/test/contract/nonforgeability.ts";
    let command_python = "bindings/python/tests/test_public_api_v2.py";
    let delegation_rust = "core/crates/auths-author/src/lib.rs";
    let delegation_typescript = "bindings/typescript/test/integration/workflow/delegation.test.js";
    let delegation_python = "bindings/python/tests/test_workflow.py";
    let lifecycle_rust = "product/runtime/auths-lifecycle/src/transition.rs";
    let runtime_typescript = "bindings/typescript/test/unit/runtime-contract.test.js";
    let runtime_python = "bindings/python/tests/test_profile_runtime_v1.py";
    let receipt_rust = "product/receipts/auths-receipts/src/lib.rs";
    let fixture_rust = "bindings/wasm/auths-proof-wasm/examples/generate-node-vectors.rs";

    vec![
        case(
            "command/forged-construction",
            "command",
            "command-not-authentic",
            command_rust,
            command_typescript,
            command_python,
        ),
        case(
            "command/serialization",
            "command",
            "command-non-serializable",
            command_rust,
            command_typescript,
            command_python,
        ),
        case(
            "command/copy",
            "command",
            "command-non-copyable",
            command_rust,
            command_typescript,
            command_python,
        ),
        case(
            "command/subclass",
            "command",
            "command-non-subclassable",
            command_rust,
            command_typescript,
            command_python,
        ),
        case(
            "command/prototype-graft",
            "command",
            "command-not-authentic",
            command_rust,
            command_typescript,
            command_python,
        ),
        case(
            "substitution/canonical-action",
            "authorization",
            "action-commitment-mismatch",
            fixture_rust,
            "bindings/typescript/test/integration/authorization-plans.test.js",
            "bindings/python/tests/test_native_authoring.py",
        ),
        case(
            "substitution/proof",
            "authorization",
            "proof-mismatch",
            fixture_rust,
            "bindings/typescript/test/integration/authorization-plans.test.js",
            "bindings/python/tests/test_native_authoring.py",
        ),
        case(
            "substitution/trusted-context",
            "authorization",
            "context-commitment-mismatch",
            fixture_rust,
            "bindings/typescript/test/integration/authorization-plans.test.js",
            "bindings/python/tests/test_native_authoring.py",
        ),
        case(
            "substitution/profile",
            "profile",
            "profile-mismatch",
            command_rust,
            command_typescript,
            command_python,
        ),
        case(
            "substitution/audience",
            "authorization",
            "audience-mismatch",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "substitution/plan-member",
            "plan",
            "plan-member-mismatch",
            command_rust,
            "bindings/typescript/test/integration/authorization-plans.test.js",
            command_python,
        ),
        case(
            "delegation/permission-widening",
            "authoring",
            "permission-expansion",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "delegation/action-widening",
            "authoring",
            "action-expansion",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "delegation/budget-widening",
            "authoring",
            "budget-expansion",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "delegation/validity-widening",
            "authoring",
            "validity-expansion",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "delegation/audience-widening",
            "authoring",
            "audience-expansion",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "delegation/status-widening",
            "authoring",
            "status-expansion",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "delegation/depth-widening",
            "authoring",
            "delegation-depth-expansion",
            delegation_rust,
            delegation_typescript,
            delegation_python,
        ),
        case(
            "state/replay",
            "reservation",
            "already-consumed",
            lifecycle_rust,
            runtime_typescript,
            runtime_python,
        ),
        case(
            "state/concurrent-reservation",
            "reservation",
            "reservation-conflict",
            lifecycle_rust,
            runtime_typescript,
            runtime_python,
        ),
        case(
            "state/wrong-order",
            "reservation",
            "invalid-transition",
            lifecycle_rust,
            runtime_typescript,
            runtime_python,
        ),
        case(
            "state/exhausted-budget",
            "reservation",
            "budget-exhausted",
            lifecycle_rust,
            runtime_typescript,
            runtime_python,
        ),
        case(
            "provider/credentials-before-reservation",
            "credentials",
            "reservation-required",
            lifecycle_rust,
            command_typescript,
            command_python,
        ),
        case(
            "provider/entry-after-denied",
            "provider",
            "provider-not-entered",
            "product/runtime/auths-runtime/src/lib.rs",
            command_typescript,
            command_python,
        ),
        case(
            "provider/entry-after-indeterminate",
            "provider",
            "provider-not-entered",
            "product/runtime/auths-runtime/src/lib.rs",
            command_typescript,
            command_python,
        ),
        case(
            "cancellation/before-provider",
            "cancellation",
            "cancelled-not-applied",
            lifecycle_rust,
            command_typescript,
            command_python,
        ),
        case(
            "cancellation/after-provider",
            "cancellation",
            "outcome-unknown",
            lifecycle_rust,
            command_typescript,
            command_python,
        ),
        case(
            "outcome/not-applied",
            "outcome",
            "safe-to-retry",
            lifecycle_rust,
            command_typescript,
            command_python,
        ),
        case(
            "outcome/applied-failure",
            "outcome",
            "applied-failure",
            lifecycle_rust,
            command_typescript,
            command_python,
        ),
        case(
            "outcome/ambiguous",
            "outcome",
            "outcome-unknown",
            lifecycle_rust,
            command_typescript,
            command_python,
        ),
        case(
            "transport/unauthorized-delivery",
            "authorization",
            "transport-is-not-authority",
            "exchange/crates/auths-proof-exchange-port/src/lib.rs",
            "bindings/typescript/test/contract/nonforgeability.ts",
            "bindings/python/tests/test_native_boundary_contract.py",
        ),
        case(
            "receipt/mutated-decision",
            "receipt",
            "receipt-commitment-mismatch",
            receipt_rust,
            "bindings/typescript/test/unit/portable-receipt-v1.test.js",
            "bindings/python/tests/test_portable_receipt_v1.py",
        ),
        case(
            "receipt/wrong-execution-link",
            "receipt",
            "receipt-link-mismatch",
            receipt_rust,
            "bindings/typescript/test/unit/portable-receipt-v1.test.js",
            "bindings/python/tests/test_portable_receipt_v1.py",
        ),
        case(
            "parity/cross-language-fixture",
            "fixture",
            "semantic-agreement",
            fixture_rust,
            "bindings/typescript/test/unit/portable-receipt-v1.test.js",
            "bindings/python/tests/test_portable_receipt_v1.py",
        ),
        case(
            "configuration/development-as-production",
            "configuration",
            "development-configuration-rejected",
            "product/config/auths-config/src/lib.rs",
            "bindings/typescript/test/unit/runtime-contract.test.js",
            "bindings/python/tools/check_contract.py",
        ),
    ]
}

fn case(
    id: &str,
    boundary: &str,
    expected: &str,
    rust: &str,
    typescript: &str,
    python: &str,
) -> ProductWaistCase {
    ProductWaistCase {
        id: id.to_owned(),
        boundary: boundary.to_owned(),
        expected: expected.to_owned(),
        evidence: ProductWaistEvidence {
            rust: rust.to_owned(),
            typescript: typescript.to_owned(),
            python: python.to_owned(),
        },
    }
}

fn valid_id(value: &str) -> bool {
    value.split('/').count() == 2
        && value.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'/')
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn simplified_product_waist_manifest_is_complete() {
        simplified_product_waist_manifest().validate().unwrap();
    }
}
