import Auths.Attenuation
import Auths.Composition
import Auths.Diversity
import Auths.Product.Theorems
import Auths.Product.Refinement
import Auths.Lifecycle.Theorems
import Auths.Lifecycle.Refinement
import Auths.Refinement.Production

namespace Auths

def theoremInventory : List Lean.Name :=
  [
    `Auths.Rich.finiteSet_subset_refl,
    `Auths.Rich.finiteSet_subset_trans,
    `Auths.Rich.finiteSet_subset_antisymm,
    `Auths.Rich.finiteSet_membership_monotone,
    `Auths.Rich.window_contained_refl,
    `Auths.Rich.window_contained_trans,
    `Auths.Rich.window_contained_antisymm,
    `Auths.Rich.window_coverage_monotone,
    `Auths.Rich.action_constraint_refl,
    `Auths.Rich.action_constraint_trans,
    `Auths.Rich.action_constraint_antisymm,
    `Auths.Rich.action_constraint_canonical_antisymm,
    `Auths.Rich.action_constraint_allows_monotone,
    `Auths.Rich.budget_refl,
    `Auths.Rich.budget_trans,
    `Auths.Rich.budget_antisymm,
    `Auths.Rich.budget_coverage_monotone,
    `Auths.Rich.status_refl,
    `Auths.Rich.status_trans,
    `Auths.Rich.status_antisymm,
    `Auths.Rich.status_satisfaction_monotone,
    `Auths.Rich.profile_refl,
    `Auths.Rich.profile_trans,
    `Auths.Rich.profile_antisymm,
    `Auths.Rich.profile_coverage_monotone,
    `Auths.Rich.structural_scope_le_refl,
    `Auths.Rich.structural_scope_le_trans,
    `Auths.Rich.scope_le_canonical_antisymmetry,
    `Auths.Rich.action_coverage_downward_closed,
    `Auths.Rich.evidence_requirements_downward_closed,
    `Auths.Rich.complete_admission_downward_closed,
    `Auths.Rich.semantic_attenuation_preorder_refl,
    `Auths.Rich.semantic_attenuation_preorder_trans,
    `Auths.Rich.structural_scope_le_implies_semantic_attenuation,
    `Auths.Rich.scope_semantic_equivalence,
    `Auths.Rich.structural_scope_le_decides_declared_v1_relation,
    `Auths.Rich.delegate_implies_scope_le,
    `Auths.Rich.delegate_preserves_root,
    `Auths.Rich.delegate_updates_subject_and_parent,
    `Auths.Rich.delegate_strict_depth,
    `Auths.Rich.delegate_never_widens,
    `Auths.Rich.remaining_depth_well_founded,
    `Auths.Rich.finite_delegation_chain,
    `Auths.Rich.chain_transitive_attenuation,
    `Auths.Rich.authorized_action_covered,
    `Auths.Rich.rich_projection_accepts_iff_scope_depth_checks,
    `Auths.Rich.apply_grant_success_iff_linked_and_projection,
    `Auths.Rich.apply_grant_success_iff_delegates,
    `Auths.Rich.apply_grant_success_unique,
    `Auths.Rich.authority_delegate_diagnostic_sound_complete,
    `Auths.Rich.authority_delegate_first_failure,
    `Auths.Rich.author_planning_diagnostic_sound_complete,
    `Auths.Rich.coverage_decision_ok_iff_covers,
    `Auths.Rich.coverage_diagnostic_sound_complete,
    `Auths.Refinement.translated_rust_refines_rich_spec,
    `Auths.Refinement.translated_coverage_refines_rich_spec,
    `Auths.Refinement.translated_delegation_refines_rich_spec,
    `Auths.Product.configuration_match_refl,
    `Auths.Product.configuration_match_deterministic,
    `Auths.Product.checked_add_never_wraps,
    `Auths.Product.checked_sub_never_underflows,
    `Auths.Product.checked_div_rejects_zero,
    `Auths.Product.three_way_partition,
    `Auths.Product.product_contract_configuration_safety,
    `Auths.Product.product_contract_output_completeness,
    `Auths.Product.Refinement.translated_configuration_refines_projection,
    `Auths.Product.Refinement.translated_checked_add_refines_nat,
    `Auths.Product.Refinement.translated_checked_sub_refines_nat,
    `Auths.Product.Refinement.translated_checked_mul_refines_nat,
    `Auths.Product.Refinement.translated_checked_div_rejects_zero,
    `Auths.Lifecycle.additive_capacity_success_positive,
    `Auths.Lifecycle.additive_capacity_success_conserves,
    `Auths.Lifecycle.additive_capacity_success_never_overflows_u64,
    `Auths.Lifecycle.reserve_preserves_capacity,
    `Auths.Lifecycle.commit_preserves_capacity,
    `Auths.Lifecycle.release_preserves_capacity,
    `Auths.Lifecycle.exact_replay_is_stable,
    `Auths.Lifecycle.conflicting_replay_is_not_exact,
    `Auths.Lifecycle.absent_replay_never_claims_effect,
    `Auths.Lifecycle.start_attempt_requires_credential,
    `Auths.Lifecycle.provider_call_requires_attempt,
    `Auths.Lifecycle.commit_requires_provider_entry_and_effect,
    `Auths.Lifecycle.outcome_unknown_cannot_release,
    `Auths.Lifecycle.outcome_unknown_only_reconciliation_can_terminate,
    `Auths.Lifecycle.configuration_mismatch_stops_reservation,
    `Auths.Lifecycle.configuration_mismatch_stops_credential,
    `Auths.Lifecycle.terminal_states_never_transition,
    `Auths.Lifecycle.Refinement.translated_terminal_refines_rich,
    `Auths.Lifecycle.Refinement.translated_transition_refines_rich,
    `Auths.Lifecycle.Refinement.translated_exclusive_capacity_refines_rich,
    `Auths.Lifecycle.Refinement.translated_additive_capacity_refines_rich,
    `Auths.Lifecycle.Refinement.translated_replay_refines_rich,
    `Auths.all_commutative,
    `Auths.all_associative,
    `Auths.all_idempotent,
    `Auths.any_commutative,
    `Auths.any_associative,
    `Auths.any_idempotent,
    `Auths.threshold_one_eq_any,
    `Auths.threshold_n_eq_all,
    `Auths.threshold_monotone_k,
    `Auths.binary_composition_swap_invariant,
    `Auths.canonical_diagnostic_permutation_invariant,
    `Auths.plan_visit_is_leaf_enumeration,
    `Auths.plan_cost_is_node_count,
    `Auths.authorized_implies_threshold_met,
    `Auths.denied_implies_threshold_impossible,
    `Auths.indeterminate_implies_threshold_reachable
  ]

end Auths
