const api=(window.AUTHS_SUBSCRIPTION_MODIFY_API_BASE||"").replace(/\/$/,"");
let session=null,experiments=[];
const $=id=>document.getElementById(id);
const request=async(path,options={})=>{const response=await fetch(api+path,{credentials:"same-origin",...options,headers:{"content-type":"application/json",...(options.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body.error||response.statusText);return body};
const money=value=>`$${(Number(value)/100).toFixed(2)} USD`;
const rows=(node,values)=>{node.innerHTML=Object.entries(values).map(([key,value])=>`<dt>${key}</dt><dd>${value}</dd>`).join("")};
function showResult(value){$("result").classList.remove("hidden");$("outcome").textContent=value.outcome||"observed";$("credentials").textContent=value.boundary?.credential_requests??"—";$("calls").textContent=value.boundary?.provider_calls??"—";$("receipt").textContent=JSON.stringify(value.receipt||value,null,2);$("receipt-link").href=value.receipt_url||"#";}
$("begin").onclick=async()=>{try{const value=await request("/api/v1/sessions",{method:"POST",body:"{}"});session=value.session_id;experiments=value.experiments;$("workspace").classList.remove("hidden");rows($("policy"),{"operation":"modify only","quantity ceiling":"2","proration debit ceiling":money(value.liability.proration_debit_minor),"recurring ceiling":money(1000),"mode":"test clock only"});rows($("action"),{"subscription":value.exact_action.subscription_id,"item":value.exact_action.before_items[0].subscription_item_id,"quantity":"1 → 2","mandate receipt":value.exact_action.mandate_receipt_digest,"protected cancel at":new Date(value.exact_action.cancel_at*1000).toISOString()});$("recurring").textContent=`${money(value.liability.before_recurring_minor)} → ${money(value.liability.after_recurring_minor)}`;$("immediate").textContent=`${money(value.liability.proration_debit_minor)} debit`;$("term").textContent=money(value.liability.incremental_term_liability_minor);$("cycles").textContent=value.liability.remaining_cycle_count;$("experiment").innerHTML=experiments.map(experiment=>`<option value="${experiment.id}">${experiment.label}</option>`).join("");$("experiment").dispatchEvent(new Event("change"));$("begin").textContent="Fixture ready";}catch(error){alert(error.message)}};
$("experiment").onchange=()=>{$("experiment-detail").textContent=experiments.find(value=>value.id===$("experiment").value)?.detail||""};
$("execute").onclick=async()=>{try{showResult(await request(`/api/v1/sessions/${session}/execute`,{method:"POST",body:JSON.stringify({experiment:$("experiment").value})}))}catch(error){alert(error.message)}};
$("reconcile").onclick=async()=>{try{showResult(await request(`/api/v1/sessions/${session}/reconcile`,{method:"POST",body:"{}"}))}catch(error){alert(error.message)}};
$("advance").onclick=async()=>{try{showResult(await request(`/api/v1/sessions/${session}/advance-clock`,{method:"POST",body:"{}"}))}catch(error){alert(error.message)}};
