"""Generated by auths; edit profile.toml, then regenerate."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, TypeVar

from auths.self_hosted import (
    EnumField,
    ExactMcpTool,
    IntegerField,
    StringField,
)

PROFILE_NAME = "stripe-refund"
PROFILE_VERSION = 1
TOOL_NAME = "create_refund_v1"
SCHEMA_DIGEST = "06c91dcf9660ed2445c04c87bd5546d8bdfb7540c3f91276685c93ea5abdd82d"


@dataclass(frozen=True)
class CreateRefund:
    operator_namespace: Literal["stripe-refunds"]
    operation_id: str
    recipe_digest: str
    payment_intent: str
    amount: int


FIELDS = {
    "operator_namespace": EnumField(('stripe-refunds',)),
    "operation_id": StringField(min_length=1, max_length=128),
    "recipe_digest": StringField(min_length=64, max_length=64),
    "payment_intent": StringField(min_length=3, max_length=255),
    "amount": IntegerField(minimum=1, maximum=99999999),
}

CommandT = TypeVar("CommandT")


def contract_for(command_type: type[CommandT]) -> ExactMcpTool[CommandT]:
    return ExactMcpTool(
        service="stripe-refunds",
        name=TOOL_NAME,
        command_type=command_type,
        fields=FIELDS,
    )


CONTRACT = contract_for(CreateRefund)
