const api=(window.AUTHS_SUBSCRIPTION_CREATE_API_BASE||"").replace(/\/$/,"");
let session=null, experiments=[];
const $=id=>document.getElementById(id);
const request=async(path,options={})=>{const r=await fetch(api+path,{credentials:"same-origin",...options,headers:{"content-type":"application/json",...(options.headers||{})}});const body=await r.json();if(!r.ok)throw new Error(body.error||r.statusText);return body};
const money=n=>`$${(Number(n)/100).toFixed(2)} USD`;
const rows=(node,values)=>{node.innerHTML=Object.entries(values).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join("")};
function showResult(value){$("result").classList.remove("hidden");$("outcome").textContent=value.outcome||"observed";$("credentials").textContent=value.boundary?.credential_requests??"—";$("calls").textContent=value.boundary?.provider_calls??"—";$("receipt").textContent=JSON.stringify(value.receipt||value,null,2);$("receipt-link").href=value.receipt_url||"#";}
$("begin").onclick=async()=>{try{const value=await request("/api/v1/sessions",{method:"POST",body:"{}"});session=value.session_id;experiments=value.experiments;$("workspace").classList.remove("hidden");rows($("policy"),{"operation":"create only","price ceiling":money(500),"term ceiling":"3 weekly cycles","active slots":"1 / customer","mode":"test clock only"});rows($("action"),{"customer":value.exact_action.customer_id,"price":value.exact_action.items[0].price_id,"payment method":value.exact_action.default_payment_method_id,"mandate receipt":value.exact_action.mandate_receipt_digest,"cancel at":new Date(value.exact_action.cancel_at*1000).toISOString()});$("recurring").textContent=money(value.liability.recurring_minor);$("immediate").textContent=money(value.liability.first_invoice_minor);$("term").textContent=money(value.liability.term_liability_minor);$("cycles").textContent=value.liability.cycle_count;$("experiment").innerHTML=experiments.map(x=>`<option value="${x.id}">${x.label}</option>`).join("");$("experiment").dispatchEvent(new Event("change"));$("begin").textContent="Fixture ready";}catch(e){alert(e.message)}};
$("experiment").onchange=()=>{$("experiment-detail").textContent=experiments.find(x=>x.id===$("experiment").value)?.detail||""};
$("execute").onclick=async()=>{try{showResult(await request(`/api/v1/sessions/${session}/execute`,{method:"POST",body:JSON.stringify({experiment:$("experiment").value})}))}catch(e){alert(e.message)}};
$("reconcile").onclick=async()=>{try{showResult(await request(`/api/v1/sessions/${session}/reconcile`,{method:"POST",body:"{}"}))}catch(e){alert(e.message)}};
$("advance").onclick=async()=>{try{showResult(await request(`/api/v1/sessions/${session}/advance-clock`,{method:"POST",body:"{}"}))}catch(e){alert(e.message)}};
