// generated by auths-profile-generator/1 from the closed profile roster.

/// Byte-sorted release artifact roles derived from the closed profile roster.
pub const QUALIFICATION_RELEASE_ARTIFACT_ROLES: &[&str] = &[
    "production-agent",
    "python-native",
    "python-profile-opentofu",
    "python-profile-postgresql",
    "python-profile-stripe",
    "python-wheel",
    "qualification-agent",
    "typescript-native",
    "typescript-package",
];
