"""Generated by auths; edit profile.toml, then regenerate."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, TypeVar

from auths.self_hosted import (
    EnumField,
    ExactMcpTool,
    IntegerField,
    StringField,
)

PROFILE_NAME = "stripe-platform-refund"
PROFILE_VERSION = 1
TOOL_NAME = "create_refund_v1"
SCHEMA_DIGEST = "d2f5b926a3b6989d13b3a4614372e298442de697d92d5e06330288f7de4e257a"


@dataclass(frozen=True)
class CreateRefund:
    operator_namespace: Literal["stripe-platform-refunds"]
    operation_id: str
    recipe_digest: str
    payment_intent: str
    amount: int
    currency: str


FIELDS = {
    "operator_namespace": EnumField(('stripe-platform-refunds',)),
    "operation_id": StringField(min_length=1, max_length=128),
    "recipe_digest": StringField(min_length=64, max_length=64),
    "payment_intent": StringField(min_length=3, max_length=255),
    "amount": IntegerField(minimum=1, maximum=99999999),
    "currency": StringField(min_length=3, max_length=3),
}

CommandT = TypeVar("CommandT")


def contract_for(command_type: type[CommandT]) -> ExactMcpTool[CommandT]:
    return ExactMcpTool(
        service="stripe-platform-refunds",
        name=TOOL_NAME,
        command_type=command_type,
        fields=FIELDS,
    )


CONTRACT = contract_for(CreateRefund)
