from typing import List, Literal, Optional, Tuple

Permission = Tuple[str, str]
Budget = Tuple[str, int]

def generate_challenge_v1() -> bytes: ...

StatusPolicy = Tuple[str, int]
CriticalExtension = Tuple[str, bytes]

class DevelopmentEd25519Key:
    @staticmethod
    def generate() -> DevelopmentEd25519Key: ...
    @staticmethod
    def from_seed(seed: bytes) -> DevelopmentEd25519Key: ...
    @property
    def principal(self) -> str: ...
    @property
    def principal_method(self) -> str: ...
    @property
    def verification_method(self) -> str: ...
    @property
    def suite(self) -> str: ...
    @property
    def evidence_type(self) -> str: ...
    @property
    def media_type(self) -> str: ...
    @property
    def evidence(self) -> bytes: ...
    def sign(self, preimage: bytes) -> bytes: ...

class DomainActionProjection:
    @property
    def media_type(self) -> str: ...
    @property
    def body(self) -> bytes: ...
    @property
    def capability(self) -> str: ...
    @property
    def resource(self) -> str: ...
    @property
    def budget(self) -> Optional[Budget]: ...
    @property
    def review_title(self) -> str: ...
    @property
    def review_fields(self) -> List[Tuple[str, str]]: ...

def canonicalize_edge_action_v1(
    fleet: str,
    device: str,
    command: str,
    sequence: int,
    state_digest: Optional[str],
) -> DomainActionProjection: ...
def parse_canonical_edge_action_v1(body: bytes) -> DomainActionProjection: ...

class ReceiptPreparation:
    @property
    def receipt_id(self) -> bytes: ...
    @property
    def canonical(self) -> bytes: ...
    @property
    def signing_preimage(self) -> bytes: ...

def prepare_authorized_decision_receipt_v1(
    proof_cbor: bytes,
    canonical_action_cbor: bytes,
    trusted_context_cbor: bytes,
    decided_at: int,
    verifier: str,
    verification_method: str,
    suite: str,
) -> ReceiptPreparation: ...
def prepare_application_execution_receipt_v1(
    decision_receipt_id_bytes: bytes,
    idempotency_key: str,
    plan_commitment: Optional[bytes],
    member_index: Optional[int],
    member_count: Optional[int],
    command_bytes: bytes,
    outcome: str,
    result: Optional[bytes],
    completed_at: int,
    verifier: str,
    verification_method: str,
    suite: str,
) -> ReceiptPreparation: ...
def attest_decision_receipt_v1(
    canonical: bytes,
    verifier: str,
    verification_method: str,
    suite: str,
    signature: bytes,
) -> bytes: ...
def attest_execution_receipt_v1(
    canonical: bytes,
    verifier: str,
    verification_method: str,
    suite: str,
    signature: bytes,
) -> bytes: ...
def verify_raw_key_receipt_v1(
    kind: str,
    attested: bytes,
    expected_id: bytes,
    verifier: str,
    verification_method: str,
    suite: str,
    raw_key_evidence: bytes,
) -> None: ...
def verify_receipt_link_v1(
    decision: bytes,
    decision_id: bytes,
    execution: bytes,
    execution_id: bytes,
) -> None: ...
def prepare_receipt_disclosure_v1(
    execution_id: bytes,
    profile_id: str,
    profile_version: int,
    command: bytes,
    result: Optional[bytes],
) -> bytes: ...
def inspect_raw_key_receipt_v1(
    decision_id: bytes,
    decision_bytes: bytes,
    decision_evidence: bytes,
    execution_id: bytes,
    execution_bytes: bytes,
    execution_evidence: bytes,
    mode: str,
    disclosure: Optional[bytes],
) -> bytes: ...

class Principal:
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...

class PrincipalDescriptor:
    def __init__(
        self,
        principal: Principal,
        principal_method: str,
        verification_method: str,
        suite: str,
    ) -> None: ...
    @property
    def principal(self) -> Principal: ...
    @property
    def principal_method(self) -> str: ...
    @property
    def verification_method(self) -> str: ...
    @property
    def suite(self) -> str: ...
    def matches(self, other: PrincipalDescriptor) -> bool: ...

class ApprovalPolicyReference:
    def __init__(
        self,
        policy_id: str,
        evaluator_version: str,
        configuration_digest: bytes,
    ) -> None: ...
    @property
    def policy_id(self) -> str: ...
    @property
    def evaluator_version(self) -> str: ...
    @property
    def configuration_digest(self) -> bytes: ...
    def matches(self, other: ApprovalPolicyReference) -> bool: ...

class UnsignedObject:
    @property
    def kind(self) -> str: ...

class SignedObject:
    @property
    def kind(self) -> str: ...

class GrantRequest:
    def __init__(
        self,
        subject: Principal,
        profile_id: str,
        profile_version: int,
        permissions: List[Permission],
        not_before: int,
        expires_at: int,
        audiences: List[str],
        body_digests: Optional[List[bytes]],
        budget: Optional[Budget],
        remaining_depth: int,
        status: Optional[StatusPolicy],
        assurance_floor: str,
        extensions: List[CriticalExtension],
    ) -> None: ...

class AuthorityDiff:
    @property
    def removed_permissions(self) -> int: ...
    @property
    def removed_audiences(self) -> int: ...
    @property
    def validity_shortened(self) -> bool: ...
    @property
    def action_narrowed(self) -> bool: ...
    @property
    def budget_narrowed(self) -> bool: ...
    @property
    def status_narrowed(self) -> bool: ...
    @property
    def delegation_depth(self) -> Tuple[int, int]: ...

class GrantPlan:
    @property
    def diff(self) -> AuthorityDiff: ...
    @property
    def warnings(self) -> List[str]: ...
    @property
    def unsigned(self) -> UnsignedObject: ...

class GrantAuthority:
    @property
    def binding(self) -> Literal["root", "delegated"]: ...
    @property
    def grant_id(self) -> bytes: ...
    @property
    def issuer(self) -> Principal: ...
    @property
    def subject(self) -> Principal: ...
    @property
    def profile(self) -> Tuple[str, int]: ...
    @property
    def permissions(self) -> List[Permission]: ...
    @property
    def validity(self) -> Tuple[int, int]: ...
    @property
    def audiences(self) -> List[str]: ...
    @property
    def action_constraint(self) -> Tuple[str, int]: ...
    @property
    def budget(self) -> Optional[Budget]: ...
    @property
    def remaining_depth(self) -> int: ...
    @property
    def parent_id(self) -> Optional[bytes]: ...
    @property
    def status(self) -> Tuple[str, Optional[str], Optional[int]]: ...
    @property
    def assurance_floor(self) -> str: ...
    @property
    def critical_extensions(self) -> List[str]: ...
    @property
    def signature(self) -> Tuple[str, str, str]: ...

class SigningRequest:
    @property
    def object_kind(self) -> str: ...
    @property
    def request_id(self) -> str: ...
    @property
    def object_id(self) -> bytes: ...
    @property
    def signing_preimage(self) -> bytes: ...
    @property
    def transaction_digest(self) -> bytes: ...
    def complete(self, signature: bytes) -> SignedObject: ...

class SigningTransaction:
    @property
    def object_kind(self) -> str: ...
    @property
    def request_id(self) -> str: ...
    @property
    def object_id(self) -> bytes: ...
    @property
    def signing_preimage(self) -> bytes: ...
    @property
    def transaction_digest(self) -> bytes: ...
    @property
    def principal(self) -> PrincipalDescriptor: ...
    @property
    def policy(self) -> ApprovalPolicyReference: ...
    @property
    def expires_at(self) -> int: ...
    @property
    def phase(
        self,
    ) -> Literal["awaiting-approval", "awaiting-signature", "terminal"]: ...
    def accept_approval(
        self,
        request_id: str,
        transaction_digest: bytes,
        policy: ApprovalPolicyReference,
        decision: str,
        now: int,
    ) -> bool: ...
    def complete_response(
        self,
        request_id: str,
        principal: PrincipalDescriptor,
        transaction_digest: bytes,
        signature: bytes,
        now: int,
    ) -> SignedObject: ...
    def discard(self) -> None: ...

class NativeDelegationExpandedError(ValueError): ...

class AuthorizationPlan:
    @property
    def plan_id(self) -> bytes: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class AuthorizationPlanBuilder:
    def __init__(self) -> None: ...
    def proof(self, reference: bytes) -> AuthorizationPlan: ...
    def all_of(self, members: List[AuthorizationPlan]) -> AuthorizationPlan: ...
    def any_of(self, members: List[AuthorizationPlan]) -> AuthorizationPlan: ...
    def threshold(
        self, required: int, members: List[AuthorizationPlan]
    ) -> AuthorizationPlan: ...

class McpAction:
    @property
    def unsigned(self) -> UnsignedObject: ...
    @property
    def audience(self) -> str: ...
    @property
    def resource(self) -> str: ...
    @property
    def display_digest_hex(self) -> str: ...
    @property
    def review_title(self) -> str: ...
    @property
    def review_fields(self) -> List[Tuple[str, str]]: ...

class McpCall:
    @property
    def service(self) -> str: ...
    @property
    def name(self) -> str: ...

class NativeMcpPlan:
    @property
    def commitment(self) -> bytes: ...
    @property
    def members(self) -> List[bytes]: ...
    @property
    def permissions(self) -> List[Permission]: ...
    @property
    def resource_namespaces(self) -> List[str]: ...
    @property
    def audiences(self) -> List[str]: ...

class McpCommand:
    @property
    def action_commitment(self) -> bytes: ...
    @property
    def authority_commitment(self) -> bytes: ...
    @property
    def context_commitment(self) -> bytes: ...
    @property
    def service(self) -> str: ...
    @property
    def name(self) -> str: ...

class McpPlanCommand:
    @property
    def count(self) -> int: ...
    @property
    def plan_commitment(self) -> bytes: ...
    @property
    def receipt_bindings(self) -> List[Tuple[bytes, bytes, bytes]]: ...

class McpGatewayCall:
    @property
    def service(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def arguments_json(self) -> bytes: ...

class McpSessionStep:
    @property
    def kind(self) -> str: ...
    @property
    def execution_id(self) -> str: ...
    @property
    def service(self) -> Optional[str]: ...
    @property
    def tool(self) -> Optional[str]: ...
    @property
    def bytes(self) -> Optional[bytes]: ...

class McpSessionTerminal:
    @property
    def kind(self) -> str: ...
    @property
    def execution_id(self) -> str: ...
    @property
    def output_json(self) -> Optional[bytes]: ...
    @property
    def receipt_json(self) -> Optional[bytes]: ...
    @property
    def reference(self) -> Optional[str]: ...
    @property
    def record_json(self) -> Optional[bytes]: ...

class McpExecutionSession:
    @property
    def execution_id(self) -> str: ...
    @property
    def canonical_action(self) -> bytes: ...
    @property
    def decision_receipt_id(self) -> bytes: ...
    @property
    def decision_receipt(self) -> bytes: ...
    @property
    def plan_commitment(self) -> Optional[bytes]: ...
    @property
    def member_index(self) -> Optional[int]: ...
    @property
    def member_count(self) -> Optional[int]: ...
    def checkpoint(self) -> McpSessionTerminal: ...
    def next_step(self) -> McpSessionStep: ...
    def accept_reservation(self, result: str) -> None: ...
    def accept_provider_entry(self) -> None: ...
    def cancel_before_provider(self) -> None: ...
    def accept_handler(
        self,
        effect: str,
        output_json: Optional[bytes] = ...,
        cause: Optional[str] = ...,
    ) -> None: ...
    def accept_receipt(self, persisted: bool) -> None: ...
    def terminal(self) -> Optional[McpSessionTerminal]: ...

class AssurancePolicy:
    def __init__(
        self,
        identifier: str,
        requirements: List[Tuple[str, str, str, Optional[int]]],
    ) -> None: ...

class TrustAnchor:
    def __init__(
        self,
        identifier: str,
        principal: Principal,
        accepted_methods: List[str],
        profiles: List[Tuple[str, int]],
        permissions: List[Permission],
        resource_namespaces: List[str],
        audiences: List[str],
        not_before: int,
        expires_at: int,
        budget: Optional[Budget],
        max_delegation_depth: int,
        assurance_policy: str,
        status: Optional[StatusPolicy],
    ) -> None: ...

class StatusSnapshot:
    @property
    def kind(self) -> str: ...

class TrustedContext:
    @property
    def configuration(self) -> bytes: ...
    def bind_request(
        self, audience: str, challenge: bytes, evaluation_time: int
    ) -> TrustedContext: ...

class VerifiedAction:
    pass

class NativeVerificationResult:
    @property
    def kind(self) -> Literal["authorized", "denied", "indeterminate"]: ...
    @property
    def code(self) -> str: ...
    @property
    def stage(
        self,
    ) -> Literal["decode", "resolve", "principal-control", "authority", "complete"]: ...
    @property
    def metrics(self) -> Tuple[int, int, int, int, int, int, int]: ...
    @property
    def required_configuration(self) -> Optional[bytes]: ...
    @property
    def local_configuration(self) -> bytes: ...
    @property
    def result_cbor(self) -> bytes: ...
    @property
    def action(self) -> Optional[VerifiedAction]: ...

class IdentityProjection:
    @property
    def method_id(self) -> str: ...
    @property
    def identity_id(self) -> str: ...
    @property
    def suite_id(self) -> str: ...
    @property
    def public_key(self) -> bytes: ...
    @property
    def packet_kind(self) -> str: ...
    @property
    def message(self) -> Optional[bytes]: ...
    @property
    def signature(self) -> Optional[bytes]: ...

RelationshipProjection = Tuple[str, str, str, List[Tuple[str, bytes]]]

class IdentityDescriptorProjection:
    @property
    def method_id(self) -> str: ...
    @property
    def identity_id(self) -> str: ...
    @property
    def method_material(self) -> bytes: ...
    @property
    def relationships(self) -> List[RelationshipProjection]: ...

class HttpCall:
    @property
    def method(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def path(self) -> str: ...

class HttpAction:
    @property
    def unsigned(self) -> UnsignedObject: ...
    @property
    def audience(self) -> str: ...
    @property
    def review_title(self) -> str: ...
    @property
    def review_fields(self) -> List[Tuple[str, str]]: ...

class HttpCommand:
    @property
    def action_commitment(self) -> bytes: ...
    @property
    def authority_commitment(self) -> bytes: ...
    @property
    def context_commitment(self) -> bytes: ...

class HttpPlanCommand:
    @property
    def count(self) -> int: ...
    @property
    def plan_commitment(self) -> bytes: ...
    @property
    def receipt_bindings(self) -> List[Tuple[bytes, bytes, bytes]]: ...

class NativeHttpPlan:
    @property
    def commitment(self) -> bytes: ...
    @property
    def members(self) -> List[bytes]: ...
    @property
    def permissions(self) -> List[Permission]: ...
    @property
    def resource_namespaces(self) -> List[str]: ...
    @property
    def audiences(self) -> List[str]: ...

class HttpGatewayRequest:
    @property
    def method(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> List[Tuple[str, List[str]]]: ...
    @property
    def headers(self) -> List[Tuple[str, str]]: ...
    @property
    def content_type(self) -> Optional[str]: ...
    @property
    def body_digest(self) -> Optional[str]: ...

class ApplicationAction:
    @property
    def profile_id(self) -> str: ...
    @property
    def profile_version(self) -> int: ...
    @property
    def media_type(self) -> str: ...
    @property
    def body(self) -> bytes: ...
    @property
    def permission(self) -> Permission: ...
    @property
    def resource_namespace(self) -> str: ...
    @property
    def audience(self) -> str: ...
    @property
    def budget(self) -> Optional[Budget]: ...

class ApplicationActionPreparation:
    @property
    def unsigned(self) -> UnsignedObject: ...

class ApplicationCommand:
    @property
    def action_commitment(self) -> bytes: ...
    @property
    def authority_commitment(self) -> bytes: ...
    @property
    def context_commitment(self) -> bytes: ...
    @property
    def profile_id(self) -> str: ...
    @property
    def profile_version(self) -> int: ...

class ApplicationPlanCommand:
    @property
    def count(self) -> int: ...
    @property
    def plan_commitment(self) -> bytes: ...
    @property
    def receipt_bindings(self) -> List[Tuple[bytes, bytes, bytes]]: ...

class NativeApplicationPlan:
    @property
    def commitment(self) -> bytes: ...
    @property
    def members(self) -> List[bytes]: ...

class ApplicationGatewayCall:
    @property
    def profile_id(self) -> str: ...
    @property
    def profile_version(self) -> int: ...
    @property
    def media_type(self) -> str: ...
    @property
    def body(self) -> bytes: ...
    @property
    def permission(self) -> Permission: ...
    @property
    def resource_namespace(self) -> str: ...
    @property
    def audience(self) -> str: ...
    @property
    def budget(self) -> Optional[Budget]: ...

def native_abi_version() -> int: ...
def approval_policy_reference(
    policy_id: str,
    evaluator_version: str,
    mode: str,
    max_uses: int,
    expires_in_seconds: int,
    requirements: List[str],
) -> ApprovalPolicyReference: ...
def validate_trusted_authority(context: TrustedContext, root: Principal) -> None: ...
def validate_root_authority(
    signed: SignedObject,
    root: Principal,
    subject: PrincipalDescriptor,
    profile_id: str,
    profile_version: int,
) -> GrantAuthority: ...
def bind_delegated_authority(
    signed: SignedObject,
    parent: GrantAuthority,
    subject: PrincipalDescriptor,
    issuer: PrincipalDescriptor,
    profile_id: str,
    profile_version: int,
) -> GrantAuthority: ...
def plan_child_fields(
    parent: GrantAuthority,
    subject: PrincipalDescriptor,
    permissions: List[Permission],
    not_before: int,
    expires_at: int,
    audiences: List[str],
    action_mode: str,
    action_digests: List[bytes],
    budget_mode: str,
    budget: Optional[Budget],
    remaining_depth: int,
    status_mode: str,
    status: Optional[StatusPolicy],
    assurance_floor: Optional[str],
) -> GrantPlan: ...
def prepare_signing_transaction(
    unsigned: UnsignedObject,
    principal: PrincipalDescriptor,
    policy: ApprovalPolicyReference,
    expires_at: int,
) -> SigningTransaction: ...
def commit_plan_approval(
    plan_commitment: bytes,
    configuration_digest: bytes,
    max_uses: int,
    expires_at: int,
) -> bytes: ...
def root_grant(issuer: Principal, request: GrantRequest) -> UnsignedObject: ...
def plan_child(parent: SignedObject, request: GrantRequest) -> GrantPlan: ...
def plan_child_statement(
    parent: UnsignedObject, request: GrantRequest
) -> GrantPlan: ...
def grant_request_from_statement(statement: UnsignedObject) -> GrantRequest: ...
def principal_status_statement(
    method: str,
    principal: Principal,
    purpose: str,
    state: str,
    sequence: int,
    observed_at: int,
    valid_until: int,
    issuer: Principal,
    extensions: List[CriticalExtension],
) -> UnsignedObject: ...
def grant_status_statement(
    method: str,
    grant_id: bytes,
    state: str,
    sequence: int,
    observed_at: int,
    valid_until: int,
    issuer: Principal,
    extensions: List[CriticalExtension],
) -> UnsignedObject: ...
def prepare_signing(
    unsigned: UnsignedObject,
    principal_method: str,
    verification_method: str,
    suite: str,
) -> SigningRequest: ...
def prepare_mcp_action(
    service: str,
    name: str,
    arguments_json: bytes,
    actor: Principal,
    terminal_grant: SignedObject,
    challenge: bytes,
    evaluation_time: int,
) -> McpAction: ...
def validate_mcp_service(service: str) -> None: ...
def mcp_call(service: str, name: str, arguments_json: bytes) -> McpCall: ...
def review_mcp_call(call: McpCall) -> Tuple[str, List[Tuple[str, str]], bytes]: ...
def commit_mcp_plan(calls: List[McpCall]) -> NativeMcpPlan: ...
def prepare_mcp_call_action(
    call: McpCall,
    actor: Principal,
    terminal_grant: SignedObject,
    challenge: bytes,
    evaluation_time: int,
) -> McpAction: ...
def authorize_mcp(
    prepared: McpAction,
    signed_action: SignedObject,
    grants: List[SignedObject],
    grant_evidence: List[List[Tuple[str, str, bytes]]],
    action_evidence: List[Tuple[str, str, bytes]],
    context: TrustedContext,
) -> Tuple[NativeVerificationResult, Optional[McpCommand]]: ...
def consume_mcp_command(
    command: McpCommand, expected_service: str
) -> McpGatewayCall: ...
def seal_mcp_plan_command(
    commands: List[McpCommand], expected_service: str, expected_commitment: bytes
) -> McpPlanCommand: ...
def consume_mcp_plan_command(
    command: McpPlanCommand, expected_service: str
) -> List[McpGatewayCall]: ...
def begin_mcp_execution(
    command: McpCommand,
    decision_receipt_id: bytes,
    decision_receipt: bytes,
    session_key: bytes,
    request_id: Optional[str] = ...,
) -> McpExecutionSession: ...
def prepare_mcp_command_decision_receipt_v1(
    command: McpCommand,
    decided_at: int,
    verifier: str,
    verification_method: str,
    suite: str,
) -> ReceiptPreparation: ...
def prepare_mcp_plan_decision_receipts_v1(
    command: McpPlanCommand,
    decided_at: int,
    verifier: str,
    verification_method: str,
    suite: str,
) -> List[ReceiptPreparation]: ...
def begin_mcp_plan_member_execution(
    command: McpPlanCommand,
    member_index: int,
    decision_receipt_id: bytes,
    decision_receipt: bytes,
    session_key: bytes,
    request_id: Optional[str] = ...,
) -> McpExecutionSession: ...
def resume_mcp_execution(
    session_key: bytes,
    reference: str,
    record_json: bytes,
) -> McpExecutionSession: ...
def status_snapshot(
    kind: str,
    identifier: bytes,
    observed_at: int,
    valid_until: int,
    statements: List[SignedObject],
    checkpoints: List[bytes],
    trust: List[Tuple[str, str, int]],
) -> StatusSnapshot: ...
def compile_trusted_context(
    configuration: bytes,
    expected_plan: Optional[AuthorizationPlan],
    minimum_authorized_branches: int,
    minimum_distinct_actors: int,
    minimum_distinct_roots: int,
    anchors: List[TrustAnchor],
    assurance_policy: AssurancePolicy,
    principal_status: Optional[StatusSnapshot],
    grant_status: Optional[StatusSnapshot],
    channel_policy: str,
    evidence_types: List[str],
    critical_extensions: List[str],
) -> TrustedContext: ...
def self_contained_configuration() -> bytes: ...
def verify_v1(
    proof_cbor: bytes,
    canonical_action_cbor: bytes,
    trusted_context_cbor: bytes,
) -> NativeVerificationResult: ...
def verify_many_v1(
    inputs: List[Tuple[bytes, bytes, bytes]],
) -> List[NativeVerificationResult]: ...
def decode_identity_v1(packet: bytes) -> IdentityProjection: ...
def encode_identity_descriptor_v1(
    method_id: str,
    identity_id: str,
    method_material: bytes,
    relationships: List[RelationshipProjection],
) -> bytes: ...
def decode_identity_descriptor_v1(packet: bytes) -> IdentityDescriptorProjection: ...
def compact_identity_descriptor_v1(packet: bytes) -> bytes: ...
def identity_descriptor_signing_preimage_v1(
    packet: bytes, relationship_id: str, message: bytes
) -> bytes: ...
def encode_public_identity_v1(
    method_id: str,
    identity_id: str,
    suite_id: str,
    public_key: bytes,
) -> bytes: ...
def raw_key_identity_v2(suite_id: str, public_key: bytes) -> bytes: ...
def validate_raw_key_identity_v2(
    method_id: str,
    identity_id: str,
    suite_id: str,
    public_key: bytes,
) -> None: ...
def identity_signing_preimage_v1(
    method_id: str,
    identity_id: str,
    suite_id: str,
    public_key: bytes,
    message: bytes,
) -> bytes: ...
def verify_ed25519_preimage_v1(
    public_key: bytes, preimage: bytes, signature: bytes
) -> None: ...
def http_call(
    method: str,
    scheme: str,
    authority: str,
    path: str,
    query: List[Tuple[str, List[str]]],
    headers: List[Tuple[str, str]],
    content_type: Optional[str],
    body_digest: Optional[str],
) -> HttpCall: ...
def review_http_call(call: HttpCall) -> Tuple[str, List[Tuple[str, str]], bytes]: ...
def commit_http_plan(calls: List[HttpCall]) -> NativeHttpPlan: ...
def prepare_http_action(
    call: HttpCall,
    actor: Principal,
    terminal_grant: SignedObject,
    challenge: bytes,
    evaluation_time: int,
) -> HttpAction: ...
def authorize_http(
    prepared: HttpAction,
    signed_action: SignedObject,
    grants: List[SignedObject],
    grant_evidence: List[List[Tuple[str, str, bytes]]],
    action_evidence: List[Tuple[str, str, bytes]],
    context: TrustedContext,
) -> Tuple[NativeVerificationResult, Optional[HttpCommand]]: ...
def inspect_http_action(action: HttpAction) -> bytes: ...
def consume_http_command(
    command: HttpCommand, expected_origin: str
) -> HttpGatewayRequest: ...
def seal_http_plan_command(
    commands: List[HttpCommand], expected_origin: str, expected_commitment: bytes
) -> HttpPlanCommand: ...
def consume_http_plan_command(
    command: HttpPlanCommand, expected_origin: str
) -> List[HttpGatewayRequest]: ...
def application_action(
    profile_id: str,
    profile_version: int,
    media_type: str,
    body: bytes,
    capability: str,
    resource: str,
    budget: Optional[Budget],
    resource_namespace: str,
    audience: str,
) -> ApplicationAction: ...
def application_action_commitment_v1(action: ApplicationAction) -> bytes: ...
def commit_application_plan(
    actions: List[ApplicationAction],
) -> NativeApplicationPlan: ...
def prepare_application_action(
    action: ApplicationAction,
    actor: Principal,
    terminal_grant: SignedObject,
    challenge: bytes,
    evaluation_time: int,
) -> ApplicationActionPreparation: ...
def authorize_application(
    prepared: ApplicationActionPreparation,
    signed_action: SignedObject,
    grants: List[SignedObject],
    grant_evidence: List[List[Tuple[str, str, bytes]]],
    action_evidence: List[Tuple[str, str, bytes]],
    context: TrustedContext,
) -> Tuple[NativeVerificationResult, Optional[ApplicationCommand]]: ...
def seal_application_plan_command(
    commands: List[ApplicationCommand],
    expected_profile_id: str,
    expected_profile_version: int,
    expected_commitment: bytes,
) -> ApplicationPlanCommand: ...
def consume_application_command(
    command: ApplicationCommand,
    expected_profile_id: str,
    expected_profile_version: int,
) -> ApplicationGatewayCall: ...
def consume_application_plan_command(
    command: ApplicationPlanCommand,
    expected_profile_id: str,
    expected_profile_version: int,
) -> List[ApplicationGatewayCall]: ...
def prepare_application_command_decision_receipt_v1(
    command: ApplicationCommand,
    decided_at: int,
    verifier: str,
    verification_method: str,
    suite: str,
) -> ReceiptPreparation: ...
def prepare_application_plan_decision_receipts_v1(
    command: ApplicationPlanCommand,
    decided_at: int,
    verifier: str,
    verification_method: str,
    suite: str,
) -> List[ReceiptPreparation]: ...
def runtime_transition_v1(
    current: Optional[str],
    operation: str,
    core_authorized: bool,
    policy_eligible: bool,
    configuration_matches: bool,
    not_revoked: bool,
    not_expired: bool,
    capacity_available: bool,
    execution_intent_present: bool,
    credential_authorized: bool,
    attempt_present: bool,
    provider_call_entered: bool,
    cancellation_allowed: bool,
    definite_effect: bool,
    definite_non_effect: bool,
    reconciliation_fresh: bool,
    reconciliation_matches: bool,
) -> Tuple[str, Optional[str]]: ...
def runtime_replay_v1(record_exists: bool, commitments_equal: bool) -> str: ...
def runtime_additive_capacity_v1(
    ceiling: int, committed: int, active: int, requested: int
) -> bool: ...
def runtime_exclusive_capacity_v1(
    has_live_owner: bool, owner_is_exact_replay: bool
) -> bool: ...
def runtime_execution_state_v1(outcome: str) -> str: ...
def runtime_application_execution_state_v1(outcome: str) -> str: ...
def decode_diagnostic_result_v1(result_cbor: bytes) -> NativeVerificationResult: ...
def commit_canonical_v1(domain: str, canonical: bytes) -> bytes: ...
def diagnostic_input_limits_v1() -> Tuple[int, int, int]: ...
def commitments_equal_v1(left: bytes, right: bytes) -> bool: ...
def inspect_verified_action(action: VerifiedAction) -> bytes: ...
def inspect_unsigned(value: UnsignedObject) -> bytes: ...
def inspect_signed(value: SignedObject) -> bytes: ...
def inspect_plan(value: AuthorizationPlan) -> bytes: ...
def inspect_mcp_action(value: McpAction) -> Tuple[bytes, bytes]: ...
def inspect_trusted_context(value: TrustedContext) -> bytes: ...
def parse_signed(kind: str, value: bytes) -> SignedObject: ...
def parse_unsigned(kind: str, value: bytes) -> UnsignedObject: ...
def parse_trusted_context(value: bytes) -> TrustedContext: ...
def unsigned_from_signed(value: SignedObject) -> UnsignedObject: ...
