"""Typed native authoring operations for higher-level Auths workflows."""

from ._native import (
    AssurancePolicy,
    AuthorityDiff,
    AuthorizationPlan,
    AuthorizationPlanBuilder,
    GrantPlan,
    GrantRequest,
    McpAction,
    Principal,
    SignedObject,
    SigningRequest,
    StatusSnapshot,
    TrustAnchor,
    TrustedContext,
    UnsignedObject,
    compile_trusted_context,
    grant_status_statement,
    grant_request_from_statement,
    native_abi_version_v1,
    plan_child,
    plan_child_statement,
    prepare_mcp_action,
    prepare_signing,
    principal_status_statement,
    root_grant,
    self_contained_configuration,
    status_snapshot,
)

ABI_VERSION = native_abi_version_v1()

__all__ = [
    "ABI_VERSION",
    "AssurancePolicy",
    "AuthorityDiff",
    "AuthorizationPlan",
    "AuthorizationPlanBuilder",
    "GrantPlan",
    "GrantRequest",
    "McpAction",
    "Principal",
    "SignedObject",
    "SigningRequest",
    "StatusSnapshot",
    "TrustAnchor",
    "TrustedContext",
    "UnsignedObject",
    "compile_trusted_context",
    "grant_status_statement",
    "grant_request_from_statement",
    "plan_child",
    "plan_child_statement",
    "prepare_mcp_action",
    "prepare_signing",
    "principal_status_statement",
    "root_grant",
    "self_contained_configuration",
    "status_snapshot",
]
