/** Generated by auths-profile; edit profile.toml, then regenerate. */
import { enumField, exactMcpTool, stringField, type CommandOf } from "@auths-dev/sdk/self-hosted";

export const PROFILE_NAME = "github-gateway-issue-create";
export const PROFILE_VERSION = 1;
export const TOOL_NAME = "create_issue_v1";
export const SCHEMA_DIGEST = "2f9c472c3681a7c7a80f6dcf057f614adbc7126f5414ca2d19c770cd050ad71f";

export const FIELDS = {
  operator_namespace: enumField(["github-demo"]),
  operation_id: stringField({ minBytes: 1, maxBytes: 64 }),
  recipe_digest: stringField({ minBytes: 64, maxBytes: 64 }),
  title: stringField({ minBytes: 1, maxBytes: 128 }),
  body: stringField({ minBytes: 0, maxBytes: 256 }),
} as const;
export type CreateIssue = CommandOf<typeof FIELDS>;
export const CONTRACT = exactMcpTool({ service: "github-gateway-demo", name: TOOL_NAME, fields: FIELDS });
