"""Generated by auths; edit profile.toml, then regenerate."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, TypeVar

from auths.self_hosted import (
    EnumField,
    ExactMcpTool,
    StringField,
)

PROFILE_NAME = "github-gateway-issue-create"
PROFILE_VERSION = 1
TOOL_NAME = "create_issue_v1"
SCHEMA_DIGEST = "2f9c472c3681a7c7a80f6dcf057f614adbc7126f5414ca2d19c770cd050ad71f"


@dataclass(frozen=True)
class CreateIssue:
    operator_namespace: Literal["github-demo"]
    operation_id: str
    recipe_digest: str
    title: str
    body: str


FIELDS = {
    "operator_namespace": EnumField(('github-demo',)),
    "operation_id": StringField(min_length=1, max_length=64),
    "recipe_digest": StringField(min_length=64, max_length=64),
    "title": StringField(min_length=1, max_length=128),
    "body": StringField(min_length=0, max_length=256),
}

CommandT = TypeVar("CommandT")


def contract_for(command_type: type[CommandT]) -> ExactMcpTool[CommandT]:
    return ExactMcpTool(
        service="github-gateway-demo",
        name=TOOL_NAME,
        command_type=command_type,
        fields=FIELDS,
    )


CONTRACT = contract_for(CreateIssue)
