events {}
http {
  upstream auths_nodes {
    server auths-1:8080;
    server auths-2:8080;
    server auths-3:8080;
  }
  server {
    listen 8443 ssl;
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols TLSv1.3;
    client_max_body_size 1m;
    location / {
      proxy_pass http://auths_nodes;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_connect_timeout 2s;
      proxy_read_timeout 15s;
      proxy_next_upstream error timeout http_502 http_503;
      proxy_next_upstream_tries 2;
    }
  }
}
