/** Generated by auths; edit profile.toml, then regenerate. */
import { enumField, exactMcpTool, stringField, type CommandOf } from "@auths-dev/sdk/self-hosted";

export const PROFILE_NAME = "airtable-gateway-record-update";
export const PROFILE_VERSION = 1;
export const TOOL_NAME = "set_demo_status_v1";
export const SCHEMA_DIGEST = "72e60b43ec96354be07e5a3a15e7a12ab6aa19b7042b757ebd05dfadcc5f2a29";

export const FIELDS = {
  operator_namespace: enumField(["airtable-demo"]),
  operation_id: stringField({ minBytes: 1, maxBytes: 128 }),
  recipe_digest: stringField({ minBytes: 64, maxBytes: 64 }),
  record_id: stringField({ minBytes: 17, maxBytes: 43 }),
  replacement: enumField(["Approved","Pending"]),
} as const;
export type SetDemoStatus = CommandOf<typeof FIELDS>;
export const CONTRACT = exactMcpTool({ service: "airtable-gateway-demo", name: TOOL_NAME, fields: FIELDS });
