"""Generated by auths; edit profile.toml, then regenerate."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, TypeVar

from auths.self_hosted import (
    EnumField,
    ExactMcpTool,
    StringField,
)

PROFILE_NAME = "airtable-gateway-record-update"
PROFILE_VERSION = 1
TOOL_NAME = "set_demo_status_v1"
SCHEMA_DIGEST = "72e60b43ec96354be07e5a3a15e7a12ab6aa19b7042b757ebd05dfadcc5f2a29"


@dataclass(frozen=True)
class SetDemoStatus:
    operator_namespace: Literal["airtable-demo"]
    operation_id: str
    recipe_digest: str
    record_id: str
    replacement: Literal["Approved", "Pending"]


FIELDS = {
    "operator_namespace": EnumField(('airtable-demo',)),
    "operation_id": StringField(min_length=1, max_length=128),
    "recipe_digest": StringField(min_length=64, max_length=64),
    "record_id": StringField(min_length=17, max_length=43),
    "replacement": EnumField(('Approved', 'Pending')),
}

CommandT = TypeVar("CommandT")


def contract_for(command_type: type[CommandT]) -> ExactMcpTool[CommandT]:
    return ExactMcpTool(
        service="airtable-gateway-demo",
        name=TOOL_NAME,
        command_type=command_type,
        fields=FIELDS,
    )


CONTRACT = contract_for(SetDemoStatus)
