[package]
name = "auths-author"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["auths-codec/std", "auths-model/std"]

[dependencies]
auths-codec.workspace = true
auths-model.workspace = true

[lints]
workspace = true
