// @generated by `cargo xtask formal --update`; DO NOT EDIT.

/// Versioned source contract used to generate this module.
pub const CONTRACT_SCHEMA: &str = "auths-proof-algebra-contract/v1";

/// Exhaustive default-deployment threshold bound.
pub const EXHAUSTIVE_THRESHOLD_BOUND: u16 = 16;

/// Closed three-valued authorization truth.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Truth {
    /// Available facts prove denial.
    Denied,
    /// Required facts are unavailable and authorization remains reachable.
    Indeterminate,
    /// Available facts prove authorization.
    Authorized,
}

/// Shared projection boundary for authority attenuation.
pub trait AttenuationProjection {
    /// Whether the trust root is preserved.
    fn root_preserved(&self) -> bool;
    /// Whether delegation depth strictly decreases.
    fn depth_decreases(&self) -> bool;
    /// Whether the selected profile does not widen.
    fn profile_attenuates(&self) -> bool;
    /// Whether permissions do not widen.
    fn permissions_attenuate(&self) -> bool;
    /// Whether the validity window does not widen.
    fn validity_attenuates(&self) -> bool;
    /// Whether audiences do not widen.
    fn audiences_attenuate(&self) -> bool;
    /// Whether the action-body constraint does not widen.
    fn action_constraint_attenuates(&self) -> bool;
    /// Whether the budget ceiling does not widen.
    fn budget_attenuates(&self) -> bool;
    /// Whether status requirements do not weaken.
    fn status_attenuates(&self) -> bool;
    /// Whether assurance requirements do not weaken.
    fn assurance_attenuates(&self) -> bool;
    /// Whether critical extensions remain exactly equal.
    fn extensions_attenuate(&self) -> bool;
}

/// Concrete projection used by vectors and bounded verification.
#[allow(
    clippy::struct_excessive_bools,
    reason = "each Boolean is one generated authority dimension"
)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AttenuationChecks {
    /// Whether the trust root is preserved.
    pub root_preserved: bool,
    /// Whether delegation depth strictly decreases.
    pub depth_decreases: bool,
    /// Whether the selected profile does not widen.
    pub profile_attenuates: bool,
    /// Whether permissions do not widen.
    pub permissions_attenuate: bool,
    /// Whether the validity window does not widen.
    pub validity_attenuates: bool,
    /// Whether audiences do not widen.
    pub audiences_attenuate: bool,
    /// Whether the action-body constraint does not widen.
    pub action_constraint_attenuates: bool,
    /// Whether the budget ceiling does not widen.
    pub budget_attenuates: bool,
    /// Whether status requirements do not weaken.
    pub status_attenuates: bool,
    /// Whether assurance requirements do not weaken.
    pub assurance_attenuates: bool,
    /// Whether critical extensions remain exactly equal.
    pub extensions_attenuate: bool,
}

impl AttenuationProjection for AttenuationChecks {
    fn root_preserved(&self) -> bool {
        self.root_preserved
    }

    fn depth_decreases(&self) -> bool {
        self.depth_decreases
    }

    fn profile_attenuates(&self) -> bool {
        self.profile_attenuates
    }

    fn permissions_attenuate(&self) -> bool {
        self.permissions_attenuate
    }

    fn validity_attenuates(&self) -> bool {
        self.validity_attenuates
    }

    fn audiences_attenuate(&self) -> bool {
        self.audiences_attenuate
    }

    fn action_constraint_attenuates(&self) -> bool {
        self.action_constraint_attenuates
    }

    fn budget_attenuates(&self) -> bool {
        self.budget_attenuates
    }

    fn status_attenuates(&self) -> bool {
        self.status_attenuates
    }

    fn assurance_attenuates(&self) -> bool {
        self.assurance_attenuates
    }

    fn extensions_attenuate(&self) -> bool {
        self.extensions_attenuate
    }
}

/// Accepts exactly when every declared attenuation dimension accepts.
#[must_use]
pub fn attenuation_accepts<P: AttenuationProjection + ?Sized>(projection: &P) -> bool {
    projection.root_preserved()
        && projection.depth_decreases()
        && projection.profile_attenuates()
        && projection.permissions_attenuate()
        && projection.validity_attenuates()
        && projection.audiences_attenuate()
        && projection.action_constraint_attenuates()
        && projection.budget_attenuates()
        && projection.status_attenuates()
        && projection.assurance_attenuates()
        && projection.extensions_attenuate()
}

/// Concrete form of the generated conjunction for mechanical translation.
#[must_use]
pub fn attenuation_checks_accept(checks: &AttenuationChecks) -> bool {
    checks.root_preserved
        && checks.depth_decreases
        && checks.profile_attenuates
        && checks.permissions_attenuate
        && checks.validity_attenuates
        && checks.audiences_attenuate
        && checks.action_constraint_attenuates
        && checks.budget_attenuates
        && checks.status_attenuates
        && checks.assurance_attenuates
        && checks.extensions_attenuate
}

/// Classifies target V1 threshold counts.
#[must_use]
pub fn threshold_counts(required: u16, authorized: usize, indeterminate: usize) -> Truth {
    let required = usize::from(required);
    if authorized >= required {
        Truth::Authorized
    } else if authorized.saturating_add(indeterminate) >= required {
        Truth::Indeterminate
    } else {
        Truth::Denied
    }
}
