#![allow(clippy::too_many_lines)]

use crate::*;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct AlgebraContract {
    schema: String,
    exhaustive_threshold_bound: u16,
    truth_order: Vec<String>,
    attenuation_acceptance: String,
    attenuation_dimensions: Vec<AlgebraDimension>,
    threshold: ThresholdContract,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct AlgebraDimension {
    rust: String,
    lean: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ThresholdContract {
    authorized: String,
    indeterminate: String,
    denied: String,
}

pub(crate) fn load_algebra_contract() -> Result<AlgebraContract, String> {
    let path = root().join("formal/algebra-contract-v1.toml");
    let contract: AlgebraContract = toml::from_str(
        &fs::read_to_string(&path)
            .map_err(|error| format!("could not read {}: {error}", path.display()))?,
    )
    .map_err(|error| format!("invalid algebra contract {}: {error}", path.display()))?;
    if contract.schema != "auths-proof-algebra-contract/v1"
        || contract.exhaustive_threshold_bound == 0
        || contract.truth_order != ["denied", "indeterminate", "authorized"]
        || contract.attenuation_acceptance != "all"
        || contract.attenuation_dimensions.is_empty()
        || contract.threshold.authorized != "authorized >= required"
        || contract.threshold.indeterminate
            != "authorized < required && authorized + indeterminate >= required"
        || contract.threshold.denied != "authorized + indeterminate < required"
    {
        return Err("unsupported algebra contract semantics".to_owned());
    }
    let rust_names: BTreeSet<_> = contract
        .attenuation_dimensions
        .iter()
        .map(|dimension| dimension.rust.as_str())
        .collect();
    let lean_names: BTreeSet<_> = contract
        .attenuation_dimensions
        .iter()
        .map(|dimension| dimension.lean.as_str())
        .collect();
    if rust_names.len() != contract.attenuation_dimensions.len()
        || lean_names.len() != contract.attenuation_dimensions.len()
    {
        return Err("algebra contract dimension names must be unique".to_owned());
    }
    Ok(contract)
}

pub(crate) fn dimension_description(name: &str) -> &'static str {
    match name {
        "root_preserved" => "the trust root is preserved",
        "depth_decreases" => "delegation depth strictly decreases",
        "profile_attenuates" => "the selected profile does not widen",
        "permissions_attenuate" => "permissions do not widen",
        "validity_attenuates" => "the validity window does not widen",
        "audiences_attenuate" => "audiences do not widen",
        "action_constraint_attenuates" => "the action-body constraint does not widen",
        "budget_attenuates" => "the budget ceiling does not widen",
        "status_attenuates" => "status requirements do not weaken",
        "assurance_attenuates" => "assurance requirements do not weaken",
        _ => "the declared authority dimension attenuates",
    }
}

pub(crate) fn render_rust_algebra(contract: &AlgebraContract) -> Result<String, String> {
    macro_rules! line {
        ($output:expr, $($argument:tt)*) => {
            writeln!($output, $($argument)*)
                .map_err(|_| "could not render generated Rust algebra".to_owned())?
        };
    }

    let mut output = String::new();
    output.push_str(
        "// @generated by `cargo xtask formal --update`; DO NOT EDIT.\n\n\
         /// Versioned source contract used to generate this module.\n",
    );
    line!(
        output,
        "pub const CONTRACT_SCHEMA: &str = {:?};",
        contract.schema
    );
    output.push_str("\n/// Exhaustive default-deployment threshold bound.\n");
    line!(
        output,
        "pub const EXHAUSTIVE_THRESHOLD_BOUND: u16 = {};",
        contract.exhaustive_threshold_bound
    );
    output.push_str(
        "\n/// Closed three-valued authorization truth.\n\
         #[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]\n\
         pub enum Truth {\n\
         \x20   /// Available facts prove denial.\n\
         \x20   Denied,\n\
         \x20   /// Required facts are unavailable and authorization remains reachable.\n\
         \x20   Indeterminate,\n\
         \x20   /// Available facts prove authorization.\n\
         \x20   Authorized,\n\
         }\n\n\
         /// Shared projection boundary for authority attenuation.\n\
         pub trait AttenuationProjection {\n",
    );
    for dimension in &contract.attenuation_dimensions {
        line!(
            output,
            "    /// Whether {}.",
            dimension_description(&dimension.rust)
        );
        line!(output, "    fn {}(&self) -> bool;", dimension.rust);
    }
    output.push_str(
        "}\n\n\
         /// Concrete projection used by vectors and bounded verification.\n\
         #[allow(\n\
         \x20   clippy::struct_excessive_bools,\n\
         \x20   reason = \"each Boolean is one generated authority dimension\"\n\
         )]\n\
         #[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
         pub struct AttenuationChecks {\n",
    );
    for dimension in &contract.attenuation_dimensions {
        line!(
            output,
            "    /// Whether {}.",
            dimension_description(&dimension.rust)
        );
        line!(output, "    pub {}: bool,", dimension.rust);
    }
    output.push_str("}\n\nimpl AttenuationProjection for AttenuationChecks {\n");
    for dimension in &contract.attenuation_dimensions {
        line!(output, "    fn {}(&self) -> bool {{", dimension.rust);
        line!(output, "        self.{}", dimension.rust);
        output.push_str("    }\n\n");
    }
    output.pop();
    output.push_str(
        "}\n\n\
         /// Accepts exactly when every declared attenuation dimension accepts.\n\
         #[must_use]\n\
         pub fn attenuation_accepts<P: AttenuationProjection + ?Sized>(projection: &P) -> bool {\n",
    );
    for (index, dimension) in contract.attenuation_dimensions.iter().enumerate() {
        let operator = if index == 0 { "    " } else { "        && " };
        line!(output, "{operator}projection.{}()", dimension.rust);
    }
    output.push_str(
        "}\n\n\
         /// Concrete form of the generated conjunction for mechanical translation.\n\
         #[must_use]\n\
         pub fn attenuation_checks_accept(checks: &AttenuationChecks) -> bool {\n",
    );
    for (index, dimension) in contract.attenuation_dimensions.iter().enumerate() {
        let operator = if index == 0 { "    " } else { "        && " };
        line!(output, "{operator}checks.{}", dimension.rust);
    }
    output.push_str(
        "}\n\n\
         /// Classifies target V1 threshold counts.\n\
         #[must_use]\n\
         pub fn threshold_counts(required: u16, authorized: usize, indeterminate: usize) -> Truth {\n\
         \x20   let required = usize::from(required);\n\
         \x20   if authorized >= required {\n\
         \x20       Truth::Authorized\n\
         \x20   } else if authorized.saturating_add(indeterminate) >= required {\n\
         \x20       Truth::Indeterminate\n\
         \x20   } else {\n\
         \x20       Truth::Denied\n\
         \x20   }\n\
         }\n",
    );
    Ok(output)
}

pub(crate) fn render_lean_algebra(contract: &AlgebraContract) -> Result<String, String> {
    macro_rules! line {
        ($output:expr, $($argument:tt)*) => {
            writeln!($output, $($argument)*)
                .map_err(|_| "could not render generated Lean algebra".to_owned())?
        };
    }

    let mut output = String::new();
    output.push_str(
        "-- @generated by `cargo xtask formal --update`; DO NOT EDIT.\n\n\
         namespace Auths.Generated\n\n",
    );
    line!(
        output,
        "def contractSchema : String := {:?}",
        contract.schema
    );
    line!(
        output,
        "\ndef exhaustiveThresholdBound : Nat := {}",
        contract.exhaustive_threshold_bound
    );
    output.push_str(
        "\ninductive Truth where\n\
         \x20 | denied\n\
         \x20 | indeterminate\n\
         \x20 | authorized\n\
         \x20 deriving BEq, DecidableEq, Repr\n\n\
         structure AttenuationProjection where\n",
    );
    for dimension in &contract.attenuation_dimensions {
        line!(output, "  {} : Bool", dimension.lean);
    }
    output.push_str("  deriving BEq, DecidableEq, Repr\n\n");
    output.push_str("def attenuationAccepts (projection : AttenuationProjection) : Bool :=\n");
    for (index, dimension) in contract.attenuation_dimensions.iter().enumerate() {
        let suffix = if index + 1 == contract.attenuation_dimensions.len() {
            ""
        } else {
            " &&"
        };
        line!(output, "  projection.{}{suffix}", dimension.lean);
    }
    output.push_str(
        "\ndef thresholdCounts (required authorized indeterminate : Nat) : Truth :=\n\
         \x20 if authorized ≥ required then .authorized\n\
         \x20 else if authorized + indeterminate ≥ required then .indeterminate\n\
         \x20 else .denied\n\n\
         end Auths.Generated\n",
    );
    Ok(output)
}

pub(crate) fn synchronize_generated_file(
    path: &Path,
    expected: &str,
    update: bool,
    label: &str,
) -> Result<(), String> {
    if update {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("could not create {}: {error}", parent.display()))?;
        }
        fs::write(path, expected)
            .map_err(|error| format!("could not write {}: {error}", path.display()))?;
        println!("Updated {label}: {}", path.display());
        return Ok(());
    }
    let actual = fs::read_to_string(path)
        .map_err(|error| format!("could not read {}: {error}", path.display()))?;
    if actual != expected {
        return Err(format!(
            "{label} drifted from formal/algebra-contract-v1.toml; run `cargo xtask formal --update`"
        ));
    }
    Ok(())
}

pub(crate) fn synchronize_algebra_sources(
    contract: &AlgebraContract,
    update: bool,
) -> Result<(), String> {
    synchronize_generated_file(
        &root().join("core/crates/auths-algebra-kernel/src/generated.rs"),
        &render_rust_algebra(contract)?,
        update,
        "generated Rust algebra",
    )?;
    synchronize_generated_file(
        &root().join("formal/Auths/Generated/Algebra.lean"),
        &render_lean_algebra(contract)?,
        update,
        "generated Lean algebra",
    )
}

pub(crate) fn synchronize_lean_vectors(formal_root: &Path, update: bool) -> Result<(), String> {
    for (kind, file) in [
        ("threshold", "threshold-counts.json"),
        ("attenuation", "attenuation-checks.json"),
        ("rich-authority", "rich-authority.json"),
    ] {
        let generated = command_output_in(
            "lake",
            &["exe", "auths-vector-export", kind],
            formal_root,
            None,
        )?;
        serde_json::from_str::<Value>(&generated)
            .map_err(|error| format!("Lean emitted invalid {kind} JSON: {error}"))?;
        synchronize_generated_file(
            &root().join("core/formal-vectors/v1").join(file),
            &generated,
            update,
            &format!("Lean-generated {kind} vectors"),
        )?;
    }
    Ok(())
}

pub(crate) fn formal(skip_kani: bool, update: bool) -> Result<(), String> {
    if !update {
        formal_qualification::validate_source_closure(&root())?;
    }
    let (formal_root, attenuation_dimensions) = prepare_formal(!skip_kani, update)?;
    formal_qualification::validate(&root(), &attenuation_dimensions)?;
    run_formal_semantic_checks(&formal_root, skip_kani, update)
}

pub(crate) fn ci_formal_translation() -> Result<(), String> {
    formal_qualification::validate_source_closure(&root())?;
    let (formal_root, attenuation_dimensions) = prepare_formal(true, false)?;
    formal_qualification::qualify(&root(), &attenuation_dimensions, false)?;
    run_formal_semantic_checks(&formal_root, false, false)
}

pub(crate) fn prepare_formal(
    require_kani: bool,
    update: bool,
) -> Result<(PathBuf, Vec<String>), String> {
    let formal_root = root().join("formal");
    let contract = load_algebra_contract()?;
    synchronize_algebra_sources(&contract, update)?;
    validate_formal_toolchain(&formal_root, require_kani)?;
    command_in("lake", &["build"], &formal_root, None)?;
    formal_assurance_audit(&formal_root, update)?;
    let attenuation_dimensions = contract
        .attenuation_dimensions
        .iter()
        .map(|dimension| dimension.rust.clone())
        .collect();
    Ok((formal_root, attenuation_dimensions))
}

pub(crate) fn run_formal_semantic_checks(
    formal_root: &Path,
    skip_kani: bool,
    update: bool,
) -> Result<(), String> {
    synchronize_lean_vectors(formal_root, update)?;

    cargo(&["test", "-p", "auths-formal-refinement"])?;
    if skip_kani {
        println!("Kani bounded harnesses:      SKIPPED (--skip-kani)");
    } else {
        command_in(
            "cargo",
            &["kani", "-p", "auths-algebra-kernel"],
            &root(),
            None,
        )?;
        command_in("cargo", &["kani", "-p", "auths-model"], &root(), None)?;
        println!("Kani bounded harnesses:      PASS");
    }
    println!("Lean theorems:              PASS");
    println!("Generated semantic vectors: byte-stable");
    println!("Rust refinement vectors:    PASS");
    Ok(())
}

pub(crate) fn validate_formal_toolchain(
    formal_root: &Path,
    require_kani: bool,
) -> Result<(), String> {
    let path = formal_root.join("translation-toolchain.lock");
    let source = fs::read_to_string(&path)
        .map_err(|error| format!("could not read {}: {error}", path.display()))?;
    let lock: toml::Value = toml::from_str(&source)
        .map_err(|error| format!("invalid formal toolchain lock {}: {error}", path.display()))?;
    if lock.get("schema").and_then(toml::Value::as_str) != Some("auths-proof-formal-toolchain/v1") {
        return Err("unsupported formal toolchain lock schema".to_owned());
    }
    let required = |table: &str, field: &str| -> Result<&str, String> {
        lock.get(table)
            .and_then(toml::Value::as_table)
            .and_then(|value| value.get(field))
            .and_then(toml::Value::as_str)
            .ok_or_else(|| format!("formal toolchain lock omits {table}.{field}"))
    };

    let rust = command_output_in("rustc", &["--version"], &root(), None)?;
    let shipping_rust = required("rust", "shipping")?;
    if !rust.contains(&format!("rustc {shipping_rust} ")) {
        return Err(format!(
            "formal shipping Rust drift: lock requires {shipping_rust}, command reported {}",
            rust.trim()
        ));
    }
    let lean = command_output_in("lean", &["--version"], formal_root, None)?;
    let lean_commit = required("lean", "commit")?;
    if !lean.contains(lean_commit) {
        return Err(format!(
            "formal Lean drift: lock requires commit {lean_commit}, command reported {}",
            lean.trim()
        ));
    }
    let lean_toolchain_path = formal_root.join("lean-toolchain");
    let lean_toolchain = fs::read_to_string(&lean_toolchain_path)
        .map_err(|error| format!("could not read {}: {error}", lean_toolchain_path.display()))?;
    if lean_toolchain.trim() != required("lean", "toolchain")? {
        return Err("formal Lean toolchain file and lock differ".to_owned());
    }
    if require_kani {
        let kani = command_output_in("kani", &["--version"], &root(), None)?;
        let kani_version = required("kani", "version")?;
        if kani.trim() != format!("kani {kani_version}") {
            return Err(format!(
                "formal Kani drift: lock requires {kani_version}, command reported {}",
                kani.trim()
            ));
        }
    }
    println!("Formal toolchain lock:       PASS");
    Ok(())
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct FormalAssuranceManifest {
    schema: String,
    lean_toolchain: String,
    toolchain_lock_sha256: String,
    allowed_axioms: Vec<String>,
    claims: Vec<FormalAssuranceClaim>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct FormalAssuranceClaim {
    claim_id: String,
    claim_text: String,
    claim_status: String,
    lean_declaration: String,
    lean_statement_sha256: String,
    formal_review: String,
    rust_symbols: Vec<String>,
    semantic_source_closure: Vec<String>,
    semantic_source_closure_sha256: String,
    evidence: Vec<FormalEvidence>,
    scope: String,
    residual_assumptions: Vec<String>,
    toolchain_lock_sha256: String,
    axioms: Vec<String>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct FormalEvidence {
    kind: String,
    artifact: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct LeanAssuranceAudit {
    schema: String,
    declarations: Vec<LeanAssuranceDeclaration>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct LeanAssuranceDeclaration {
    name: String,
    kind: String,
    statement: String,
    axioms: Vec<String>,
}

pub(crate) fn formal_assurance_audit(formal_root: &Path, update: bool) -> Result<(), String> {
    let manifest_path = formal_root.join("assurance-manifest-v1.toml");
    let mut manifest: FormalAssuranceManifest = toml::from_str(
        &fs::read_to_string(&manifest_path)
            .map_err(|error| format!("could not read {}: {error}", manifest_path.display()))?,
    )
    .map_err(|error| {
        format!(
            "invalid assurance manifest {}: {error}",
            manifest_path.display()
        )
    })?;
    if manifest.schema != "auths-proof-formal-assurance/v1" {
        return Err(format!(
            "unsupported formal assurance schema {}",
            manifest.schema
        ));
    }

    let lean_toolchain_path = formal_root.join("lean-toolchain");
    let lean_toolchain = fs::read_to_string(&lean_toolchain_path)
        .map_err(|error| format!("could not read {}: {error}", lean_toolchain_path.display()))?;
    if lean_toolchain.trim() != manifest.lean_toolchain {
        return Err("formal assurance manifest Lean toolchain drifted".to_owned());
    }

    let toolchain_lock_path = formal_root.join("translation-toolchain.lock");
    let toolchain_lock_digest = sha256_file(&toolchain_lock_path)?;
    if manifest.toolchain_lock_sha256 != toolchain_lock_digest {
        return Err(format!(
            "formal toolchain lock drifted: expected {}, found {toolchain_lock_digest}",
            manifest.toolchain_lock_sha256
        ));
    }

    let audit_output = command_output_in(
        "lake",
        &["env", "lean", "Auths/AssuranceAudit.lean"],
        formal_root,
        None,
    )?;
    let audit: LeanAssuranceAudit = serde_json::from_str(audit_output.trim())
        .map_err(|error| format!("compiled Lean assurance audit emitted invalid JSON: {error}"))?;
    if audit.schema != "auths-proof-lean-assurance-audit/v1" {
        return Err(format!(
            "unsupported compiled Lean assurance audit schema {}",
            audit.schema
        ));
    }

    if update {
        synchronize_formal_assurance_manifest(
            formal_root,
            &manifest_path,
            &mut manifest,
            &audit,
            &toolchain_lock_digest,
        )?;
    }

    let allowed_axioms: BTreeSet<_> = manifest.allowed_axioms.iter().cloned().collect();
    if allowed_axioms.len() != manifest.allowed_axioms.len() || allowed_axioms.contains("sorryAx") {
        return Err("formal assurance axiom allowlist is duplicate or permits sorryAx".to_owned());
    }

    let mut compiled = BTreeMap::new();
    for declaration in audit.declarations {
        let name = declaration.name.clone();
        if compiled.insert(name.clone(), declaration).is_some() {
            return Err(format!(
                "compiled Lean assurance audit repeated declaration {name}"
            ));
        }
    }
    let mut reviewed = BTreeSet::new();
    let mut claim_ids = BTreeSet::new();
    for claim in &manifest.claims {
        if !claim_ids.insert(claim.claim_id.clone()) {
            return Err(format!(
                "formal assurance manifest repeated claim id {}",
                claim.claim_id
            ));
        }
        if !reviewed.insert(claim.lean_declaration.clone()) {
            return Err(format!(
                "formal assurance manifest repeated declaration {}",
                claim.lean_declaration
            ));
        }
        for (field, value) in [
            ("claim_id", claim.claim_id.as_str()),
            ("claim_text", claim.claim_text.as_str()),
            ("formal_review", claim.formal_review.as_str()),
            ("scope", claim.scope.as_str()),
        ] {
            if value.trim().is_empty() {
                return Err(format!(
                    "formal claim {} has empty {field}",
                    claim.lean_declaration
                ));
            }
        }
        if !matches!(
            claim.claim_status.as_str(),
            "proved" | "qualified" | "assumed"
        ) {
            return Err(format!(
                "formal claim {} has unsupported status {}",
                claim.lean_declaration, claim.claim_status
            ));
        }
        if claim.toolchain_lock_sha256 != toolchain_lock_digest {
            return Err(format!(
                "formal claim {} has stale toolchain lock digest",
                claim.lean_declaration
            ));
        }
        if claim.semantic_source_closure.is_empty()
            || claim.evidence.is_empty()
            || claim.residual_assumptions.is_empty()
        {
            return Err(format!(
                "formal claim {} must declare source closure, evidence, and residual assumptions",
                claim.lean_declaration
            ));
        }
        let closure_digest = semantic_source_closure_digest(&claim.semantic_source_closure)?;
        if closure_digest != claim.semantic_source_closure_sha256 {
            return Err(format!(
                "formal claim {} semantic source closure drifted: expected {}, found {closure_digest}",
                claim.lean_declaration, claim.semantic_source_closure_sha256
            ));
        }
        for symbol in &claim.rust_symbols {
            if symbol.trim().is_empty() {
                return Err(format!(
                    "formal claim {} contains an empty Rust symbol",
                    claim.lean_declaration
                ));
            }
        }
        for item in &claim.evidence {
            if item.kind.trim().is_empty() || item.artifact.trim().is_empty() {
                return Err(format!(
                    "formal claim {} contains incomplete evidence",
                    claim.lean_declaration
                ));
            }
            let artifact = root().join(&item.artifact);
            if !artifact.exists() {
                return Err(format!(
                    "formal claim {} evidence artifact does not exist: {}",
                    claim.lean_declaration,
                    artifact.display()
                ));
            }
        }

        let declaration = compiled.get(&claim.lean_declaration).ok_or_else(|| {
            format!(
                "reviewed Lean declaration {} is absent from the compiled environment",
                claim.lean_declaration
            )
        })?;
        if declaration.kind != "theorem" {
            return Err(format!(
                "reviewed declaration {} is {}, not theorem",
                claim.lean_declaration, declaration.kind
            ));
        }
        let statement_digest = hex::encode(Sha256::digest(declaration.statement.as_bytes()));
        if statement_digest != claim.lean_statement_sha256 {
            return Err(format!(
                "Lean statement drift for {}: expected {}, found {statement_digest}",
                claim.lean_declaration, claim.lean_statement_sha256
            ));
        }
        let actual_axioms: BTreeSet<_> = declaration.axioms.iter().cloned().collect();
        let reviewed_axioms: BTreeSet<_> = claim.axioms.iter().cloned().collect();
        if actual_axioms != reviewed_axioms {
            return Err(format!(
                "Lean axiom drift for {}: reviewed={reviewed_axioms:?}, compiled={actual_axioms:?}",
                claim.lean_declaration
            ));
        }
        if let Some(unapproved) = actual_axioms.difference(&allowed_axioms).next() {
            return Err(format!(
                "Lean declaration {} transitively depends on unapproved axiom {unapproved}",
                claim.lean_declaration
            ));
        }
    }

    let compiled_names: BTreeSet<_> = compiled.keys().cloned().collect();
    if reviewed != compiled_names {
        return Err(format!(
            "compiled and reviewed Lean claim inventories differ: reviewed={reviewed:?}, compiled={compiled_names:?}"
        ));
    }
    let evidence_directory = root().join("target/formal");
    fs::create_dir_all(&evidence_directory).map_err(|error| {
        format!(
            "could not create formal evidence directory {}: {error}",
            evidence_directory.display()
        )
    })?;
    let mut evidence = serde_json::to_vec_pretty(
        &serde_json::from_str::<Value>(audit_output.trim())
            .map_err(|error| format!("could not normalize Lean assurance evidence: {error}"))?,
    )
    .map_err(|error| format!("could not encode Lean assurance evidence: {error}"))?;
    evidence.push(b'\n');
    fs::write(
        evidence_directory.join("lean-assurance-audit.json"),
        evidence,
    )
    .map_err(|error| format!("could not write Lean assurance evidence: {error}"))?;
    println!(
        "Formal assurance audit:     PASS ({} compiled statements; transitive axioms reviewed)",
        reviewed.len()
    );
    Ok(())
}

pub(crate) fn synchronize_formal_assurance_manifest(
    formal_root: &Path,
    manifest_path: &Path,
    manifest: &mut FormalAssuranceManifest,
    audit: &LeanAssuranceAudit,
    toolchain_lock_digest: &str,
) -> Result<(), String> {
    let source_closure = vec![
        "formal/Auths/Base.lean".to_owned(),
        "formal/Auths/Authority.lean".to_owned(),
        "formal/Auths/Attenuation.lean".to_owned(),
        "formal/Auths/Rich/Types.lean".to_owned(),
        "formal/Auths/Rich/Semantics.lean".to_owned(),
        "formal/Auths/Rich/Theorems.lean".to_owned(),
        "formal/Auths/Product/Commitment.lean".to_owned(),
        "formal/Auths/Product/Arithmetic.lean".to_owned(),
        "formal/Auths/Product/Eligibility.lean".to_owned(),
        "formal/Auths/Product/Tightening.lean".to_owned(),
        "formal/Auths/Product/Theorems.lean".to_owned(),
        "formal/Auths/Product/Refinement.lean".to_owned(),
        "formal/Auths/Lifecycle/Semantics.lean".to_owned(),
        "formal/Auths/Lifecycle/Theorems.lean".to_owned(),
        "formal/Auths/Refinement/Production.lean".to_owned(),
        "formal/Auths/Composition.lean".to_owned(),
        "formal/Auths/Diversity.lean".to_owned(),
        "formal/Auths/Generated/Algebra.lean".to_owned(),
        "formal/Auths/Theorems.lean".to_owned(),
        "formal/qualification/aeneas/generated/authority/Funs.lean".to_owned(),
        "formal/qualification/aeneas/generated/authority/Types.lean".to_owned(),
        "formal/qualification/aeneas/generated/bounded_policy/Funs.lean".to_owned(),
        "formal/qualification/aeneas/generated/bounded_policy/Types.lean".to_owned(),
        "formal/qualification/aeneas/generated/model/Funs.lean".to_owned(),
        "formal/qualification/aeneas/generated/model/Types.lean".to_owned(),
        "formal/algebra-contract-v1.toml".to_owned(),
    ];
    let source_closure_digest = semantic_source_closure_digest(&source_closure)?;
    let mut rich_index = manifest
        .claims
        .iter()
        .filter_map(|claim| claim.claim_id.strip_prefix("AP-FORMAL-RICH-"))
        .filter_map(|suffix| suffix.parse::<usize>().ok())
        .max()
        .unwrap_or(0);
    let mut existing: BTreeMap<_, _> = std::mem::take(&mut manifest.claims)
        .into_iter()
        .map(|claim| (claim.lean_declaration.clone(), claim))
        .collect();
    let mut claims = Vec::with_capacity(audit.declarations.len());
    for declaration in &audit.declarations {
        let statement_digest = hex::encode(Sha256::digest(declaration.statement.as_bytes()));
        let mut claim = if let Some(claim) = existing.remove(&declaration.name) {
            claim
        } else {
            rich_index += 1;
            let short_name = declaration
                .name
                .rsplit('.')
                .next()
                .unwrap_or(&declaration.name);
            let phrase = short_name.replace('_', " ");
            let is_product = declaration.name.starts_with("Auths.Product.");
            let is_lifecycle = declaration.name.starts_with("Auths.Lifecycle.");
            FormalAssuranceClaim {
                claim_id: format!("AP-FORMAL-RICH-{rich_index:03}"),
                claim_text: if is_lifecycle {
                    format!("Lean proves the reservation/execution lifecycle property: {phrase}.")
                } else if is_product {
                    format!("Lean proves the bounded product-policy property: {phrase}.")
                } else {
                    format!("Lean proves the rich authority property: {phrase}.")
                },
                claim_status: "proved".to_owned(),
                lean_declaration: declaration.name.clone(),
                lean_statement_sha256: String::new(),
                formal_review: "rich-authority-refinement-2026-07-29".to_owned(),
                rust_symbols: Vec::new(),
                semantic_source_closure: Vec::new(),
                semantic_source_closure_sha256: String::new(),
                evidence: vec![FormalEvidence {
                    kind: "lean-proof".to_owned(),
                    artifact: if is_lifecycle {
                        "formal/Auths/Lifecycle/Theorems.lean".to_owned()
                    } else if is_product {
                        "formal/Auths/Product/Theorems.lean".to_owned()
                    } else {
                        "formal/Auths/Rich/Theorems.lean".to_owned()
                    },
                }],
                scope: if is_lifecycle {
                    "Pure V1 lifecycle transitions, capacity conservation, replay, configuration gates, credential ordering, provider entry, and reconciliation.".to_owned()
                } else if is_product {
                    "Pure V1 bounded product-policy commitments, checked arithmetic, configuration gating, and eligibility.".to_owned()
                } else {
                    "Rich target-V1 authority semantics over opaque identity carriers and extensional finite sets.".to_owned()
                },
                residual_assumptions: vec![
                    "Lean's kernel, the pinned toolchain, the listed foundational axioms, and the theorem premises are trusted.".to_owned(),
                ],
                toolchain_lock_sha256: String::new(),
                axioms: Vec::new(),
            }
        };
        claim.lean_statement_sha256 = statement_digest;
        claim.semantic_source_closure.clone_from(&source_closure);
        claim
            .semantic_source_closure_sha256
            .clone_from(&source_closure_digest);
        claim.toolchain_lock_sha256 = toolchain_lock_digest.to_owned();
        claim.axioms.clone_from(&declaration.axioms);
        claims.push(claim);
    }
    if !existing.is_empty() {
        println!(
            "Formal assurance update:    removed {} declarations absent from compiled inventory",
            existing.len()
        );
    }
    manifest.claims = claims;
    let rendered = toml::to_string_pretty(manifest)
        .map_err(|error| format!("could not render formal assurance manifest: {error}"))?;
    fs::write(manifest_path, format!("{}\n", rendered.trim_end()))
        .map_err(|error| format!("could not write {}: {error}", manifest_path.display()))?;
    println!(
        "Formal assurance update:    {} compiled claims synchronized",
        manifest.claims.len()
    );
    let _ = formal_root;
    Ok(())
}

pub(crate) fn semantic_source_closure_digest(paths: &[String]) -> Result<String, String> {
    let mut ordered = paths.to_vec();
    ordered.sort();
    ordered.dedup();
    if ordered.len() != paths.len() {
        return Err("semantic source closure paths must be unique".to_owned());
    }
    let mut digest = Sha256::new();
    for relative in ordered {
        let path = root().join(&relative);
        if !path.is_file() {
            return Err(format!(
                "semantic source closure entry is not a file: {}",
                path.display()
            ));
        }
        digest.update(relative.as_bytes());
        digest.update([0]);
        digest.update(
            fs::read(&path)
                .map_err(|error| format!("could not read {}: {error}", path.display()))?,
        );
        digest.update([0xff]);
    }
    Ok(hex::encode(digest.finalize()))
}

pub(crate) fn formal_qualify_aeneas(update: bool) -> Result<(), String> {
    let (_, attenuation_dimensions) = prepare_formal(false, update)?;
    formal_qualification::qualify(&root(), &attenuation_dimensions, update)
}
