// generated by auths-profile-generator/1 from the closed profile roster.
//! Static qualification-time provider adapter registration.

use crate::profile_qualification::{
    CleanupAdapterContext, ObserveAdapterContext, RunAdapterContext, cleanup_domain_adapter,
    observe_domain_adapter, run_domain_adapter,
};
use auths_profile_kit::{
    QualificationEffect, QualificationHarnessError, QualificationOperationRole,
    QualificationProtectedObserver, QualificationProtectedSetup, QualificationProtectedSetupInput,
    QualificationProviderTruth, QualificationRedactedOperation, QualificationScenarioProgramV1,
    QualificationSetupHandoffV1,
};

pub(crate) fn qualification_domain_scenario_ids(
    domain: &str,
) -> Result<&'static [&'static str], String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_domain_scenario_ids()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_domain_scenario_ids()),
        "stripe" => Ok(auths_stripe::qualification::qualification_domain_scenario_ids()),
        _ => Err("qualification domain has no generated scenario roster".into()),
    }
}

pub(crate) fn qualification_requirement_ids(
    domain: &str,
) -> Result<&'static [&'static str], String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_requirement_ids()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_requirement_ids()),
        "stripe" => Ok(auths_stripe::qualification::qualification_requirement_ids()),
        _ => Err("qualification domain has no generated requirement roster".into()),
    }
}

pub(crate) fn qualification_receipt_claim_ids(
    domain: &str,
) -> Result<&'static [&'static str], String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_receipt_claim_ids()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_receipt_claim_ids()),
        "stripe" => Ok(auths_stripe::qualification::qualification_receipt_claim_ids()),
        _ => Err("qualification domain has no generated receipt-claim roster".into()),
    }
}

pub(crate) fn qualification_provider_truth_fields(
    domain: &str,
) -> Result<&'static [&'static str], String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_provider_truth_fields()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_provider_truth_fields()),
        "stripe" => Ok(auths_stripe::qualification::qualification_provider_truth_fields()),
        _ => Err("qualification domain has no generated provider-truth field roster".into()),
    }
}

pub(crate) fn qualification_forbidden_evidence_fields(
    domain: &str,
) -> Result<&'static [&'static str], String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_forbidden_evidence_fields()),
        "postgresql" => {
            Ok(auths_postgresql::qualification::qualification_forbidden_evidence_fields())
        }
        "stripe" => Ok(auths_stripe::qualification::qualification_forbidden_evidence_fields()),
        _ => Err("qualification domain has no generated forbidden-evidence field roster".into()),
    }
}

pub(crate) fn qualification_redaction_prefixes(
    domain: &str,
) -> Result<&'static [&'static str], String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_redaction_prefixes()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_redaction_prefixes()),
        "stripe" => Ok(auths_stripe::qualification::qualification_redaction_prefixes()),
        _ => Err("qualification domain has no generated redaction-prefix roster".into()),
    }
}

pub(crate) fn qualification_requirements_sha256(domain: &str) -> Result<&'static str, String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_requirements_sha256()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_requirements_sha256()),
        "stripe" => Ok(auths_stripe::qualification::qualification_requirements_sha256()),
        _ => Err("qualification domain has no generated requirement inventory digest".into()),
    }
}

pub(crate) fn qualification_provider_matrix_rows(
    domain: &str,
) -> Result<
    &'static [(
        &'static str,
        &'static str,
        &'static str,
        &'static str,
        &'static str,
    )],
    String,
> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_provider_matrix_rows()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_provider_matrix_rows()),
        "stripe" => Ok(auths_stripe::qualification::qualification_provider_matrix_rows()),
        _ => Err("qualification domain has no generated provider-matrix row roster".into()),
    }
}

pub(crate) fn qualification_operation_plan(
    domain: &str,
) -> Result<&'static [(QualificationOperationRole, &'static str, bool, bool)], String> {
    match domain {
        "opentofu" => Ok(auths_opentofu::qualification::qualification_operation_plan()),
        "postgresql" => Ok(auths_postgresql::qualification::qualification_operation_plan()),
        "stripe" => Ok(auths_stripe::qualification::qualification_operation_plan()),
        _ => Err("qualification domain has no generated operation-plan roster".into()),
    }
}

pub(crate) fn run_protected_setup(
    input: QualificationProtectedSetupInput<'_>,
    setup_credential: &[u8],
) -> Result<QualificationSetupHandoffV1, String> {
    let result = match input.run_context.protected_environment.as_str() {
        "qualification-opentofu" => auths_opentofu::qualification::OpentofuQualificationAdapter
            .setup(input, setup_credential),
        "qualification-postgresql" => {
            auths_postgresql::qualification::PostgresqlQualificationAdapter
                .setup(input, setup_credential)
        }
        "qualification-stripe" => {
            auths_stripe::qualification::StripeQualificationAdapter.setup(input, setup_credential)
        }
        _ => {
            return Err(
                "qualification domain is absent from the generated static setup roster".into(),
            );
        }
    };
    result.map_err(|error| error.to_string())
}

pub(crate) fn run_collection_adapter(context: RunAdapterContext<'_>) -> Result<(), String> {
    match context.domain {
        "opentofu" => run_domain_adapter(
            auths_opentofu::qualification::OpentofuQualificationAdapter,
            context,
        ),
        "postgresql" => run_domain_adapter(
            auths_postgresql::qualification::PostgresqlQualificationAdapter,
            context,
        ),
        "stripe" => run_domain_adapter(
            auths_stripe::qualification::StripeQualificationAdapter,
            context,
        ),
        _ => Err("qualification domain is absent from the generated static adapter roster".into()),
    }
}

pub(crate) fn validate_provider_truth_facts(
    domain: &str,
    bytes: &[u8],
    effect: QualificationEffect,
) -> Result<(), String> {
    let result = match domain {
        "opentofu" => auths_opentofu::qualification::validate_provider_truth_facts(bytes, effect),
        "postgresql" => {
            auths_postgresql::qualification::validate_provider_truth_facts(bytes, effect)
        }
        "stripe" => auths_stripe::qualification::validate_provider_truth_facts(bytes, effect),
        _ => return Err("qualification domain has no generated provider-truth validator".into()),
    };
    result.map_err(|error| error.to_string())
}

pub(crate) fn validate_provider_matrix_contract(
    domain: &str,
    bytes: &[u8],
    provider_version: &str,
    provider_artifact_sha256: &str,
) -> Result<(), String> {
    let result = match domain {
        "opentofu" => auths_opentofu::qualification::validate_provider_matrix_contract(
            bytes,
            provider_version,
            provider_artifact_sha256,
        ),
        "postgresql" => auths_postgresql::qualification::validate_provider_matrix_contract(
            bytes,
            provider_version,
            provider_artifact_sha256,
        ),
        "stripe" => auths_stripe::qualification::validate_provider_matrix_contract(
            bytes,
            provider_version,
            provider_artifact_sha256,
        ),
        _ => return Err("qualification domain has no generated provider-matrix validator".into()),
    };
    result.map_err(|error| error.to_string())
}

pub(crate) fn validate_domain_scenario(
    domain: &str,
    program: &QualificationScenarioProgramV1,
    operations: &[QualificationRedactedOperation],
    truths: &[QualificationProviderTruth],
) -> Result<(), String> {
    let result: Result<(), QualificationHarnessError> = match domain {
        "opentofu" => auths_opentofu::qualification::OpentofuQualificationAdapter
            .validate_domain_scenario(program, operations, truths),
        "postgresql" => auths_postgresql::qualification::PostgresqlQualificationAdapter
            .validate_domain_scenario(program, operations, truths),
        "stripe" => auths_stripe::qualification::StripeQualificationAdapter
            .validate_domain_scenario(program, operations, truths),
        _ => return Err("qualification domain has no generated scenario validator".into()),
    };
    result.map_err(|error| error.to_string())
}

pub(crate) fn run_protected_observer(context: ObserveAdapterContext<'_>) -> Result<(), String> {
    match context.domain {
        "opentofu" => observe_domain_adapter(
            auths_opentofu::qualification::OpentofuQualificationAdapter,
            context,
        ),
        "postgresql" => observe_domain_adapter(
            auths_postgresql::qualification::PostgresqlQualificationAdapter,
            context,
        ),
        "stripe" => observe_domain_adapter(
            auths_stripe::qualification::StripeQualificationAdapter,
            context,
        ),
        _ => Err("qualification domain is absent from the generated static observer roster".into()),
    }
}

pub(crate) fn run_protected_cleanup(context: CleanupAdapterContext<'_>) -> Result<(), String> {
    match context.domain {
        "opentofu" => cleanup_domain_adapter(
            auths_opentofu::qualification::OpentofuQualificationAdapter,
            context,
        ),
        "postgresql" => cleanup_domain_adapter(
            auths_postgresql::qualification::PostgresqlQualificationAdapter,
            context,
        ),
        "stripe" => cleanup_domain_adapter(
            auths_stripe::qualification::StripeQualificationAdapter,
            context,
        ),
        _ => Err("qualification domain is absent from the generated static cleanup roster".into()),
    }
}
