import { loadPackagedWorkflowEngine } from "./verifier/wasm.js";
import { createWorkflowClient, type LoadWorkflowOptions } from "./workflow.js";

export {
  AuthsClient,
  AuthsWorkflowError,
  AttachedAgent,
  ProviderOperationError,
  SignedGrantSource,
  TrustedContextSource,
  type AgentIdentity,
  type ApprovalConfiguration,
  type ApprovalExecutionSummary,
  type ApprovalMode,
  type ApprovalPolicy,
  type ApprovalPolicyReference,
  type ApprovalProvider,
  type ApprovalRequest,
  type ApprovalResponse,
  type AttachAgentOptions,
  type AuthorizationResult,
  type AuthorizedCommandResult,
  type AuthorityDiffSummary,
  type ControlEvidence,
  type DelegatedActionConstraint,
  type DelegatedAuthorityRequest,
  type DelegatedBudget,
  type DelegatedStatus,
  type DelegationOptions,
  type DelegationReview,
  type EffectState,
  type EffectiveAuthoritySummary,
  type ErrorContext,
  type ErrorFamily,
  type OverGrantingWarning,
  type PermissionSummary,
  type PlanAuthorizationResult,
  type PrincipalDescriptor,
  type Profile,
  type ProviderFailureKind,
  type RetryClass,
  type ReviewField,
  type SignedGrantLoadRequest,
  type SignedGrantMaterial,
  type SignedGrantProvider,
  type SignedGrantSourceOptions,
  type Signer,
  type SignerLifecycle,
  type SigningObjectKind,
  type SigningRequest,
  type SigningResponse,
  type TrustedAuthority,
  type TrustedAuthoritySnapshot,
  type TrustedContextLoadRequest,
  type TrustedContextProvider,
  type TrustedContextSourceOptions,
  type WorkflowErrorCode,
  type WorkflowVerificationResult,
  signedGrantSource,
  trustedContextSource,
} from "./workflow.js";

export type LoadAuthsOptions = LoadWorkflowOptions;

export async function loadAuths(options: LoadAuthsOptions) {
  return createWorkflowClient(options, await loadPackagedWorkflowEngine());
}
