apiVersion: v1
kind: ServiceAccount
metadata:
  name: auths-node
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/REPLACE_AUTHORIZED_KMS_SIGNER_ROLE
automountServiceAccountToken: true
