/** Generated by auths; edit profile.toml, then regenerate. */
import { enumField, exactMcpTool, stringField, type CommandOf } from "@auths-dev/sdk/self-hosted";

export const PROFILE_NAME = "todoist-gateway-task-create";
export const PROFILE_VERSION = 1;
export const TOOL_NAME = "create_task_v1";
export const SCHEMA_DIGEST = "d2929455f9e255caf23629daa0db125c73565a2a55b4db13fbe0fbea731d10f3";

export const FIELDS = {
  operator_namespace: enumField(["todoist-demo"]),
  operation_id: stringField({ minBytes: 1, maxBytes: 128 }),
  recipe_digest: stringField({ minBytes: 64, maxBytes: 64 }),
  content: stringField({ minBytes: 1, maxBytes: 256 }),
  description: stringField({ minBytes: 1, maxBytes: 80 }),
  temp_id: stringField({ minBytes: 36, maxBytes: 36 }),
} as const;
export type CreateTask = CommandOf<typeof FIELDS>;
export const CONTRACT = exactMcpTool({ service: "todoist-gateway-demo", name: TOOL_NAME, fields: FIELDS });
