"""Generated by auths; edit profile.toml, then regenerate."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, TypeVar

from auths.self_hosted import (
    EnumField,
    ExactMcpTool,
    StringField,
)

PROFILE_NAME = "todoist-gateway-task-create"
PROFILE_VERSION = 1
TOOL_NAME = "create_task_v1"
SCHEMA_DIGEST = "d2929455f9e255caf23629daa0db125c73565a2a55b4db13fbe0fbea731d10f3"


@dataclass(frozen=True)
class CreateTask:
    operator_namespace: Literal["todoist-demo"]
    operation_id: str
    recipe_digest: str
    content: str
    description: str
    temp_id: str


FIELDS = {
    "operator_namespace": EnumField(('todoist-demo',)),
    "operation_id": StringField(min_length=1, max_length=128),
    "recipe_digest": StringField(min_length=64, max_length=64),
    "content": StringField(min_length=1, max_length=256),
    "description": StringField(min_length=1, max_length=80),
    "temp_id": StringField(min_length=36, max_length=36),
}

CommandT = TypeVar("CommandT")


def contract_for(command_type: type[CommandT]) -> ExactMcpTool[CommandT]:
    return ExactMcpTool(
        service="todoist-gateway-demo",
        name=TOOL_NAME,
        command_type=command_type,
        fields=FIELDS,
    )


CONTRACT = contract_for(CreateTask)
