"""Generated by auths; edit profile.toml, then regenerate."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, TypeVar

from auths.self_hosted import (
    EnumField,
    ExactMcpTool,
    IntegerField,
    StringField,
)

PROFILE_NAME = "stripe-refund"
PROFILE_VERSION = 1
TOOL_NAME = "create_refund_v1"
SCHEMA_DIGEST = "db3a47820a6f5c3ce3883068bea16542721e049cab8453a2af579c77a46d5c5e"


@dataclass(frozen=True)
class CreateRefund:
    operator_namespace: Literal["stripe-refunds"]
    operation_id: str
    recipe_digest: str
    payment_intent: str
    amount: int
    connect_account: str
    currency: str


FIELDS = {
    "operator_namespace": EnumField(('stripe-refunds',)),
    "operation_id": StringField(min_length=1, max_length=128),
    "recipe_digest": StringField(min_length=64, max_length=64),
    "payment_intent": StringField(min_length=3, max_length=255),
    "amount": IntegerField(minimum=1, maximum=99999999),
    "connect_account": StringField(min_length=13, max_length=64),
    "currency": StringField(min_length=3, max_length=3),
}

CommandT = TypeVar("CommandT")


def contract_for(command_type: type[CommandT]) -> ExactMcpTool[CommandT]:
    return ExactMcpTool(
        service="stripe-refunds",
        name=TOOL_NAME,
        command_type=command_type,
        fields=FIELDS,
    )


CONTRACT = contract_for(CreateRefund)
