#!/usr/bin/env node

/** Restricted source generator; never loads provider credentials or trust. */

import { lstat, mkdir, readFile, realpath, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const identity = /^[a-z][a-z0-9._-]{0,63}$/;
const key = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;
const tool = /^[A-Za-z][A-Za-z0-9._-]{0,111}$/;
const quoted = /^"([A-Za-z0-9_.:-]+)"$/;
const integer = /^(0|[1-9][0-9]{0,8})$/;
const reserved = new Set(["__proto__", "prototype", "constructor"]);

export function parseContract(source) {
  if (new TextEncoder().encode(source).length > 16_384) throw new Error("profile.toml exceeds 16 KiB");
  const sections = new Map();
  let current;
  for (const original of source.split(/\r?\n/)) {
    const line = original.trim();
    if (line === "" || line.startsWith("#")) continue;
    if (line === "[profile]" || line === "[fields]") {
      current = line.slice(1, -1);
      if (sections.has(current)) throw new Error("duplicate profile section");
      sections.set(current, new Map());
      continue;
    }
    const separator = line.indexOf("=");
    if (current === undefined || separator < 0) throw new Error("invalid profile.toml line");
    const name = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    const entries = sections.get(current);
    if (!key.test(name) || reserved.has(name) || entries.has(name)) throw new Error("invalid or duplicate profile key");
    const match = quoted.exec(value);
    if (match) entries.set(name, match[1]);
    else if (integer.test(value)) entries.set(name, Number(value));
    else throw new Error("unsupported profile.toml value");
  }
  if (sections.size !== 2 || !sections.has("profile") || !sections.has("fields")) {
    throw new Error("profile and fields sections are required");
  }
  const profile = sections.get("profile");
  if (["name", "version", "service", "tool"].some(name => !profile.has(name)) ||
      [...profile.keys()].some(name => !["name", "version", "service", "tool", "command"].includes(name))) {
    throw new Error("profile identity fields are invalid");
  }
  const name = profile.get("name");
  const version = profile.get("version");
  const service = profile.get("service");
  const baseTool = profile.get("tool");
  const command = profile.get("command") ?? name.split(/[-_.]/).map(part => part[0].toUpperCase() + part.slice(1)).join("");
  const versionedTool = `${baseTool}_v${version}`;
  if (typeof name !== "string" || !identity.test(name) ||
      !Number.isInteger(version) || version < 1 || version > 9999 ||
      typeof service !== "string" || !identity.test(service) ||
      typeof baseTool !== "string" || !tool.test(baseTool) ||
      new TextEncoder().encode(versionedTool).length > 128 ||
      typeof command !== "string" || !key.test(command) || reserved.has(command)) {
    throw new Error("profile identity or version is invalid");
  }
  const rawFields = sections.get("fields");
  if (rawFields.size < 1 || rawFields.size > 32) throw new Error("command field count is outside bounds");
  const fields = [];
  for (const [fieldName, value] of rawFields) {
    if (reserved.has(fieldName) || typeof value !== "string") throw new Error("invalid command field");
    const parts = value.split(":");
    const kind = parts[0];
    if (["boolean", "optional-boolean"].includes(kind) && parts.length === 1) {
      fields.push({ name: fieldName, kind });
      continue;
    }
    if (!["string", "optional-string", "integer", "optional-integer"].includes(kind) || parts.length !== 3 ||
        !/^-?(0|[1-9][0-9]*)$/.test(parts[1]) || !/^-?(0|[1-9][0-9]*)$/.test(parts[2])) {
      throw new Error("unsupported command field schema");
    }
    const minimum = Number(parts[1]);
    const maximum = Number(parts[2]);
    if (!Number.isSafeInteger(minimum) || !Number.isSafeInteger(maximum) ||
        (kind.endsWith("string")
          ? minimum < 0 || minimum > maximum || maximum > 4096
          : minimum > maximum)) {
      throw new Error("command field bounds are invalid");
    }
    fields.push({ name: fieldName, kind, minimum, maximum });
  }
  return { name, version, service, tool: versionedTool, command, fields };
}

function fieldSource(field) {
  const inner = field.kind.endsWith("string")
    ? `stringField({ minBytes: ${field.minimum}, maxBytes: ${field.maximum} })`
    : field.kind.endsWith("integer")
      ? `integerField({ minimum: ${field.minimum}, maximum: ${field.maximum} })`
      : "booleanField()";
  return field.kind.startsWith("optional-") ? `optionalField(${inner})` : inner;
}

export function renderGenerated(contract) {
  const fields = contract.fields.map(field => `  ${field.name}: ${fieldSource(field)},`).join("\n");
  return `/** Generated by auths profile; edit profile.toml, then regenerate. */\n` +
    `import { booleanField, exactMcpTool, integerField, optionalField, stringField, type CommandOf } from "@auths-dev/sdk/self-hosted";\n\n` +
    `export const PROFILE_NAME = "${contract.name}";\n` +
    `export const PROFILE_VERSION = ${contract.version};\n` +
    `export const TOOL_NAME = "${contract.tool}";\n\n` +
    `export const FIELDS = {\n${fields}\n} as const;\n` +
    `export type ${contract.command} = CommandOf<typeof FIELDS>;\n` +
    `export const CONTRACT = exactMcpTool({ service: "${contract.service}", name: TOOL_NAME, fields: FIELDS });\n`;
}

function stableJson(value) {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (value !== null && typeof value === "object") {
    return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

export function renderVectors(contract) {
  const valid = Object.fromEntries(contract.fields.map(field => [field.name,
    field.kind.startsWith("optional-") ? null
      : field.kind === "string" ? "x".repeat(field.minimum)
      : field.kind === "integer" ? field.minimum : false,
  ]));
  return stableJson({
    schema: "auths.self-hosted-profile-vectors/1",
    profile: contract.name,
    version: contract.version,
    service: contract.service,
    tool: contract.tool,
    valid_arguments_json: stableJson(valid),
  }) + "\n";
}

async function sourceAt(path) {
  const metadata = await lstat(path);
  if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size > 16_384) {
    throw new Error("profile.toml must be a bounded regular file");
  }
  return readFile(path, "utf8");
}

async function writeProfile(directory, contract) {
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, "generated.ts"), renderGenerated(contract));
  await writeFile(join(directory, "vectors.json"), renderVectors(contract));
}

async function checkProfile(path) {
  const contract = parseContract(await sourceAt(path));
  const directory = dirname(path);
  const problems = [];
  for (const [name, expected] of [
    ["generated.ts", renderGenerated(contract)],
    ["vectors.json", renderVectors(contract)],
  ]) {
    let actual;
    try { actual = await readFile(join(directory, name), "utf8"); } catch { actual = undefined; }
    if (actual !== expected) problems.push(`${name} has drifted`);
  }
  return problems;
}

async function main(args) {
  if (args.length === 1 && args[0] === "doctor") {
    const { doctor, renderDoctor } = await import("../dist/doctor.js");
    process.stdout.write(`${renderDoctor(await doctor())}\n`);
    return;
  }
  if (args[0] !== "profile") throw new Error("usage: auths profile init|generate|check|doctor");
  const action = args[1];
  if (action === "init") {
    const languageAt = args.indexOf("--language");
    const nameAt = args.indexOf("--name");
    const directoryAt = args.indexOf("--directory");
    if (languageAt < 0 || args[languageAt + 1] !== "typescript" || nameAt < 0 ||
        !identity.test(args[nameAt + 1] ?? "")) throw new Error("init requires --language typescript and bounded --name");
    const name = args[nameAt + 1];
    const directory = directoryAt < 0 ? "." : args[directoryAt + 1];
    if (!directory) throw new Error("--directory needs a path");
    const source = `[profile]\nname = "${name}"\nversion = 1\nservice = "${name}"\ntool = "invoke"\n\n[fields]\nvalue = "string:1:256"\n`;
    await mkdir(directory, { recursive: true });
    for (const filename of ["profile.toml", "generated.ts", "vectors.json"]) {
      try { await stat(join(directory, filename)); throw new Error("profile files already exist"); }
      catch (error) { if (error.code !== "ENOENT") throw error; }
    }
    await writeFile(join(directory, "profile.toml"), source, { flag: "wx" });
    await writeProfile(directory, parseContract(source));
    process.stdout.write(`created ${join(directory, "profile.toml")}; self-hosted, provider behavior unqualified\n`);
    return;
  }
  const path = args[2] ?? "profile.toml";
  if (action === "generate") {
    await writeProfile(dirname(path), parseContract(await sourceAt(path)));
    process.stdout.write(`generated ${dirname(path)}; self-hosted, provider behavior unqualified\n`);
  } else if (action === "check") {
    const problems = await checkProfile(path);
    if (problems.length) throw new Error(problems.join("; "));
    process.stdout.write("profile current; self-hosted, provider behavior unqualified\n");
  } else if (action === "doctor") {
    const problems = await checkProfile(path);
    if (problems.length) throw new Error(problems.join("; "));
    process.stdout.write("contract: current; provider adapter: application-owned, unqualified\n");
    if (args.includes("--production")) {
      const option = name => { const at = args.indexOf(name); return at < 0 ? undefined : args[at + 1]; };
      const signer = option("--signer-adapter");
      const grant = option("--grant-file");
      const trust = option("--trust-file");
      if (!identity.test(signer ?? "") || !grant || !trust) {
        throw new Error("production needs --signer-adapter, --grant-file, and --trust-file");
      }
      for (const filename of [grant, trust]) {
        const metadata = await lstat(filename);
        if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size < 1 || metadata.size > 262_144) {
          throw new Error("production authority file is unavailable or outside bounds");
        }
      }
      if (await realpath(grant) === await realpath(trust)) throw new Error("grant and trusted context need separate files");
      process.stdout.write("production inputs: structurally present; signer connectivity and trust provenance not checked\n");
    } else {
      process.stdout.write("local testkit authority is development-only\n");
    }
    process.stdout.write("profile doctor does not verify provider credentials or qualify adapter behavior\n");
  } else {
    throw new Error("usage: auths profile init|generate|check|doctor");
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch(error => {
    process.stderr.write(`auths profile: ${error instanceof Error ? error.message : "unknown failure"}\n`);
    process.exitCode = 1;
  });
}
